import { SpeakerProps } from "./speakerProps"

export const randyNOrsby : SpeakerProps = {
    id : 'randy-n-orsby',
    speakerTopic: 'buildingCapacity',
    // reverse : false,
    image : '/events/symposium/2026-speakers/randy-orsby.webp',
    name : 'Randy N. Orsby',
    bio : ` <p>Randy N. Orsby has a long tenure (37 years) within the Logistics and Supply Chain Industry. His profession started out as a young 18 year old in 1985 in the U.S. Air Force in the Requisition & Purchasing area procuring different types of munitions and explosive material for the Department of Defense. As he transitioned from different bases, he started procuring aircraft equipment along with air-to-air combat missiles for the F-111 Fighter Aircrafts. His additional duties were managing the inventory levels of the stored equipment and nuclear weapons.</p>
            <p>After an honorable discharge from the military, he attended and graduated from Memphis State University gaining an undergraduate degree in Business Finance. A few years later, he attended the University of Memphis and obtained his MBA with a concentration in both Finance and Economics. While attending the university, he started working for an esteemed company of FedEx (Headquartered in Memphis, TN) which he learned more about the logistics industry and how important it is to the nations GDP and the world’s GNP. He worked his way up to management in operations before deciding to advance his career in the corporate sector. As a Senior Supply Chain Specialist in the Air Operations Division, he procured material and equipment which helped him gain an enormous amount of knowledge about engineering and reengineering of aircrafts such as the Boeing’s 727, 757, MD10-10, MD10-30, MD11, and the AirBus A-310 & A-300 fleets.</p>
            <p>He later took a job at Memphis Light, Gas & Water as the Supervisor of Purchasing which is responsible for the procurement of all goods and some services at the Division. After nine years in that role, he has become the Manager of Procurement & Contracts and Supplier Diversity. This position has created a passion for providing the opportunity to do business with minority, women-owned and local small businesses. His constant focus is on increasing the Division percentage diversity spend each year through the process of purchasing material or contract services. He is a current member of MMBC who works with other advocacy agencies to promote local growth in our community. He also is a member of NIGP and ISM.</p>
            <p>In addition to his work history and education, Randy is involved in community activities, which he is a member of the prestigious fraternity of Kappa Alpha Psi Fraternity, Incorporated for approximately 30 years. He helps young men of Kappa League learn how to be progressive young adults in today’s society.</p>
            <p>Randy believes in equality and equity for all. When this is demanded and received, we as human will succeed in all endeavors of life.</p>`
}