export const blackMenOfMemphis = {
    memberStatus: false,
    id : "100-black-men-of-memphis",
    businessName : "100 Black Men of Memphis",
    bannerImage : "",
    profileLogo : "100blackmen",
    profileDescription : "100 Black Men of Memphis (100BMOM) is a nonprofit mentoring and community-serving organization focused on empowering African American youth through programs in mentoring, education, economic development, and health & wellness.",
    profileCategory : "education-training-youth-development",
    profileSubCategory : ["schools-colleges-universities",
                "skills-development-training-centres",
                "online-learning",
                "personal-development-coacing",
                "youth-programs-tutoring",
                
        ],
    profileBusinessDescription : ``,
    businessHours : {
        monHours : "",
        tueHours : "",
        wedHours : "",
        thuHours : "",
        friHours : "",
        satHours : "",
        sunHours : ""
    },
    addressLink : "",
    address : "",
    email : "darrell@universalcommercial.com",
    website : "https://100bmom.org/",
    telNumber : "",
    facebook : "https://www.facebook.com/100BMOM/",
    instagram : "https://www.instagram.com/100bmom/",
    youtube : "",
    linkedIn : "",
    linktree : "",
    twitter: "",
    tiktok : "",
    pinterest : ""
}