export const DreamLife = {
    id : "1800dreamlife",
    businessName : "1800Dreamlife",
    bannerImage : "",
    profileLogo : "1800dreamlife",
    profileDescription : "1800Dreamlife is a full-service branding and printing studio offering custom branding packages, custom-printed collateral, apparel, and digital support tailored for small businesses, startups, and professionals—combining creativity, precision, and hands-on support to bring your vision to life.",
    profileCategory : "marketing-advertising-media",
    profileSubCategory : [
                "website-design-development",
                "graphic-design",
                "branding-visual-identity",
                "marketing-material-print-media",
            ],
    profileBusinessDescription : ``,
    businessHours : {
        monHours : "Closed",
        tueHours : "Closed",
        wedHours : "10am - 6pm",
        thuHours : "10am - 6pm",
        friHours : "10am - 6pm",
        satHours : "Closed",
        sunHours : "Closed"
    },
    addressLink : "https://maps.app.goo.gl/n4sbhkoT5eYYzd7k8",
    address : "3845 Viscount Ave Suite 104, Memphis, TN 38118",
    email : "1800dreamlife@gmail.com",
    website : "https://1800dreamlife.com/",
    telNumber : "9017309035",
    facebook : "https://www.facebook.com/1800dreamlife",
    instagram : "",
    youtube : "",
    linkedIn : "",
    linktree : "",
    twitter: "",
    tiktok : "",
    pinterest : ""
}