export const thirdEyeView = {
    memberStatus: false,
    id : "3rdeyeview",
    businessName : "3rdEyeView",
    bannerImage : "",
    profileLogo : "3rdeyeview",
    profileDescription : "3rdEyeView is a Memphis-based nonprofit and eyewear brand dedicated to eliminating poor vision among children through free screenings, exams, and glasses. Blending community impact with cutting-edge style, the organization promotes the link between healthy vision and educational success—one pair of glasses at a time.",
    profileCategory : [
        "health-wellness-personal-care",
        "community-government-non-profits",
    ],
    profileSubCategory : [
        "medical-healthcare-professionals",
        "ngo-charities",
    ],
    profileBusinessDescription : ``,
    gallery : [],
    businessHours : {
        monHours : "",
        tueHours : "",
        wedHours : "",
        thuHours : "",
        friHours : "",
        satHours : "",
        sunHours : ""
    },
    addressLink : "",
    address : "",
    email : "contact@shop3rdeyeview.com",
    website : "https://www.shop3rdeyeview.com/",
    telNumber : "9014963180",
    facebook : "http://www.facebook.com/iiirdeyeview",
    instagram : "http://instagram.com/iiirdeyeview",
    youtube : "",
    linkedIn : "",
    linktree : "",
    twitter: "http://twitter.com/iiirdeyeview",
    tiktok : "",
    pinterest : ""
}