export const fourDMarketingBusinessSolutionsFirm = {
    id : "4d-marketing-business-solutions-firm",
    businessName : "4D Marketing & Business Solutions Firm",
    bannerImage : "",
    profileLogo : "4dmarketing",
    profileDescription : "4D Marketing & Business Solutions Firm is a full-service Memphis‑based marketing and business solutions agency offering digital marketing, branding, web design, advertising, and end-to-end support services including legal, insurance, hosting, and more.",
    profileCategory : "marketing-advertising-media",
    profileSubCategory : [
        "digital-media-content-creators",
        "website-design-development",
        "branding-visual-identity",
    ],
    profileBusinessDescription : ``,
    gallery : [],
    businessHours : {
        monHours : "",
        tueHours : "",
        wedHours : "",
        thuHours : "",
        friHours : "",
        satHours : "",
        sunHours : ""
    },
    addressLink : "",
    address : "3725 Champion Hills Dr, Ste 3200, Memphis, Tn, 38125",
    email : "z4dmarketing.biz.rn@outlook.com",
    website : "https://4dmarketingbusinesssolutions.com/",
    telNumber : "9014148098",
    facebook : "https://www.facebook.com/4D-Marketing-Business-Solutions-Firm-143496266400653/",
    instagram : "https://www.instagram.com/z4dmarketing/",
    youtube : "https://www.youtube.com/watch?v=Bhlf5D967tQ",
    linkedIn : "",
    linktree : "",
    twitter: "https://www.twitter.com/z4dmarketing",
    tiktok : "",
    pinterest : "https://www.pinterest.com/z4dmarketingbiz"
}