export const nineOoneParties = {
    id : "901-parties",
    businessName : "901PATIES",
    bannerImage : "",
    profileLogo : "901parties",
    profileDescription : "901PARTIES Memphis provides turnkey event rentals—including bounce houses, carnival rides, video game trucks, face painters, and 360° photo booths—for birthdays, schools, churches, and more. With easy online quotes and family-friendly packages, they make party planning effortless and festive across the Memphis area.",
    profileCategory : "event-arts-entertainment",
    profileSubCategory : [
        "party-rentals-entertainment-specialists",
        "event-catering-concession-services",
        "event-planning-services",
    ],
    profileBusinessDescription : ``,
    gallery : [],
    businessHours : {
        monHours : "24 Hours",
        tueHours : "24 Hours",
        wedHours : "24 Hours",
        thuHours : "24 Hours",
        friHours : "24 Hours",
        satHours : "24 Hours",
        sunHours : "24 Hours"
    },
    addressLink : "https://share.google/0JH6J5XYnGj7EmMfC",
    address : "1299 Southland Mall, Memphis, TN 38116",
    email : "info@901parties.com",
    website : "https://901parties.com/",
    telNumber : "9014913183",
    facebook : "https://www.facebook.com/901partiesmobiledininigandcatering",
    instagram : "https://www.instagram.com/901parties_memphis/",
    youtube : "https://www.youtube.com/channel/UCbrP4ePyW_shASvgkXZGl7g",
    linkedIn : "",
    linktree : "",
    twitter: "https://www.twitter.com/901parties",
    tiktok : "",
    pinterest : ""
}