export interface EventListType {
    holidayStatus: boolean,
    id : string,
    path? : string,
    type: string,
    eventImage : string,
    eventImageAlt : string,
    eventDate : string,
    sortDate : string,
    eventTime : string,
    eventAddressLink : string,
    eventAddress : string,
    eventName : string,
    eventDescription : string,
    eventLongDescription: string,
    eventPastDescription: string,
    eventPastBlog: string,
    eventCTAbuttonLink : string,
    eventCTAbuttonText : string,
    registrationButtonText : string,
    registrationButtonLink : string,
    eventGallery? : {src: string, alt: string,}[],
}

// holidayStatus: "",
// id : "",
// type: '',
// eventImage : "",
// eventImageAlt : "",
// eventDate : "",
// sortDate : "",
// eventTime : "",
// eventAddressLink : "",
// eventAddress : "",
// eventName : "",
// eventDescription : "",
// eventLongDescription : "",
// eventPastDescription: "",
// eventPastBlog: ``,
// eventCTAbuttonLink : "",
// eventCTAbuttonText : "",
// eventGallery: [{src: "", alt: ""}]