import { ResourcesType } from "../resourcesType";

export const dummy : ResourcesType = {
    id : '',
    mainImage : '/resources/',
    mainImageWidth : 831,
    mainImageHeight : 440,
    logo : '/resources/',
    logoWidth : 300,
    logoHeight : 244,
    articleTitle : '',
    blogTitle : '',
    readPath : '/resources/',
    description : ``,
    offerings : [
        {
            offerName : '',
            offerType : '',
            offerColor : ''
        },
    ],
    serveStage : [],
    mainCategory : 'insights',
    filterCategory : [
        'funding', 
        'training', 
        'mentorship', 
        'compliance', 
        'procurement', 
        'marketing',
    ],
    subCategory : [
        'loans', 
        'grants', 
        'investors', 
        'cdfis', 
        'workshops', 
        'programs', 
        'certifications', 
        'bootcamps', 
        'business-advisors', 
        'mentor-programs', 
        'peer-groups', 
        'licensing', 
        'legal', 
        'accounting', 
        'insurance', 
        'supplier-readiness', 
        'bid-opportunities', 
        'government-contracts', 
        'websites', 
        'social-media', 
        'brand-strategy',
    ],
    // blog section
    introHeading : 'Who They Are',
    introParagraph : `<p></p>`,
    whosHeading : 'Who is this for?',
    whosParagraph : ``,
    whosImage : '',
    whosImagealt : '',
    whosImageWidth : 300,
    whosImageHeight : 300,
    offerBlockHeading : 'What They Offer Entrepreneurs',
    offerBlockText : ``,
    ctaOneText : "",
    ctaOneButton : 'Learn More',
    ctaOneLink : '',
    ctaTwoText : "",
    ctaTwoButton : "Start Your Application",
    ctaTwoLink : ''
}