import { ResourcesType } from "../resourcesType";

export const dmc : ResourcesType = {
    id : 'downtown-memphis-commission',
    mainImage : '/resources/',
    mainImageWidth : 831,
    mainImageHeight : 440,
    logo : '/resources/',
    logoWidth : 300,
    logoHeight : 244,
    articleTitle : 'Downtown Memphis Commission',
    blogTitle : 'Downtown Memphis Commission — Your Partner in Building a Business Downtown',
    readPath : '/resources/downtown-memphis-commission',
    description : `The Downtown Memphis Commission (DMC) is the go-to resource for entrepreneurs looking to open or grow a business in the heart of Memphis, offering grants, development programs, and incentives to make it happen.`,
    offerings : [
        {
            offerName : 'Emerging Developers Program',
            offerType : 'Program',
            offerColor : 'blue'
        },{
            offerName : 'Renovation Incentives',
            offerType : 'Resource',
            offerColor : 'green'
        },{
            offerName : 'Limited Marketing Support',
            offerType : 'Resource',
            offerColor : 'green'
        }
    ],
    serveStage : ['Small Business'],
    mainCategory : 'insights',
    filterCategory : ['training', 'mentorship'],
    subCategory : ['workshops', 'programs', 'business-advisors', 'mentor-programs', 'peer-groups',],
    // blog section
    introHeading : 'Who They Are',
    introParagraph : `<p>The Downtown Memphis Commission (DMC) drives Downtown's role as the economic, cultural, and governmental core of the city and county. But beyond being a civic organization, the DMC is one of the most practical and entrepreneur-friendly resources available to anyone looking to open or grow a business in the heart of Memphis.</p>
                        <p>The DMC is funded by an assessment on commercial property in the Central Business Improvement District (CBID), which is reinvested into funding incentives and activations designed to support the growth of both Downtown's population and appraised commercial property values. In plain terms: the DMC takes money generated by Downtown and puts it back into making Downtown a better place to do business.</p>
                        <p>The DMC's two primary metrics for success are an increase in the number of people living, working and engaging in Downtown, and an increase in Downtown commercial property values. This means the DMC has a direct, vested interest in helping your business succeed.</p>`,
    whosHeading : 'Who is this for?',
    whosParagraph : `<p>The Downtown Memphis Commission is the right resource for you if you are:</p>
                    <ul>
                        <li>An entrepreneur looking to open a retail, food & beverage, or creative arts business in Downtown Memphis</li>
                        <li>A developer — new or experienced — interested in building or renovating property Downtown</li>
                        <li>A business owner wanting to improve your existing Downtown location</li>
                        <li>Someone exploring Downtown Memphis as a location to launch or expand your business</li>`,
    whosImage : '',
    whosImagealt : '',
    whosImageWidth : 300,
    whosImageHeight : 300,
    offerBlockHeading : 'What They Offer Entrepreneurs',
    offerBlockText : `<h3 class="globalThirdHeading">Grants & Financial Incentives for Entrepreneurs</h3>
                        <p class="globalText">The DMC offers a robust suite of grants and programs specifically designed to reduce the financial barriers of starting or improving a Downtown business. Here are the most relevant ones for entrepreneurs:</p>
                        <h3 class="globalThirdHeading" style="margin-top:4rem">Retail Tenant Improvement (TI) Grant</h3>
                        <p class="globalText">This is one of the most valuable programs available to new Downtown businesses. The Downtown Retail Tenant Improvement Grant is designed to help grow a vibrant and thriving retail climate in Downtown Memphis, supporting new retail, creative arts & entertainment, and food & beverage businesses who choose to locate within key corridors and retail nodes.</p>
                        <p class="globalText">The Retail TI Grant helps bridge the financial gap between property owners and tenants by providing reimbursement for qualified permanent interior improvements. Grants of up to $30,000 are available per project, with an increased maximum of $45,000 for eligible businesses with frontage along the Main Street Pedestrian Mall.</p>
                        <p class="globalText">What can the grant cover? Eligible expenses include hazardous materials abatement, interior demolition and shell reconstruction, ADA compliance, permanent equipment, plumbing, mechanical, electrical & HVAC, permanent lighting, flooring, windows, doors, commercial storefront, historic restoration of interior features, and architectural/interior design and permitting fees.</p>
                        <p class="globalText">Who can apply? The grant is designed for tenants who will sign a lease with a minimum term of 12 months to occupy ground-floor space. Applicants must apply for and receive approval of a Retail TI Grant prior to signing their lease.</p>
                        <h3 class="globalThirdHeading" style="margin-top:4rem">Additional Incentive Programs</h3>
                        <p class="globalText">Beyond the Retail TI Grant, the DMC offers a full menu of incentives, including:</p>
                        <ul class="globalText">
                            <li><strong>Exterior Improvement Grant</strong> — for improving the outside appearance of your building</li>
                            <li><strong>Good Neighbor Grant</strong> — supporting property upkeep and community standards</li>
                            <li><strong>Open on Main</strong> — incentives specifically for businesses opening on the Main Street corridor</li>
                            <li><strong>Table Ready</strong> — support for food & beverage businesses getting up and running</li>
                            <li><strong>Development Loan</strong> — financing for larger development projects</li>
                            <li><strong>Downtown Pre-Development Assistance Grant</strong> — helping developers cover early-stage costs before a project begins</li>
                            <li><strong>Sidewalk Repair Grant</strong> — for property owners addressing public-facing infrastructure</li>
                            <li><strong>MLGW / TVA Incentive</strong> — energy-related incentives for Downtown properties</li>
                        </ul>
                        <p class="globalText">All programs are administered through the DMC and applications are reviewed on a case-by-case basis.</p>
                        <h3 class="globalThirdHeading" style="margin-top:4rem">The Emerging Developer Program</h3>
                        <p class="globalText">If you're interested in real estate development — not just opening a business, but actually developing property — the DMC has a dedicated pathway for you.</p>
                        <p class="globalText">The Emerging Developer program includes classes and workshops designed to help prepare participants for a career in commercial development, with the goal of creating a stronger and more equitable community beginning with those who are actively engaged in creating the built environment.</p>
                        <p class="globalText">The program's core curriculum includes:</p>
                        <ul class="globalText">
                            <li><strong>Em-Dev Develop-A-Thon</strong> — A one and a half-day workshop for emerging developers to create pitch-ready presentations to approach investors with. This is ideal for anyone who has a development concept but doesn't yet know how to package it for funding conversations.</li>
                            <li><strong>Em-Dev Local</strong> — These programs are offered throughout the year and are designed specifically to help Emerging Developers navigate the local development ecosystem. Classes are open to the public, and participants do not have to have an actual site or project to participate.</li>
                        </ul>
                        <h3 class="globalThirdHeading" style="margin-top:4rem">Getting Your Business Listed & Visible</h3>
                        <p class="globalText">Once your business is open Downtown, the DMC can help you get discovered. Entrepreneurs can submit their business to the Downtown Directory — a public-facing resource used by residents, workers, and visitors to find businesses in the area. This is a free and easy way to increase your visibility in the heart of the city.</p>
                        <h3 class="globalThirdHeading" style="margin-top:4rem">Events & Community Activation</h3>
                        <p class="globalText">The DMC creates and/or supports multiple Downtown events, with nearly 200 free events each year, further investing in a Downtown that is attractive to residents, office workers, and visitors. For business owners, this means a steady stream of foot traffic driven directly to your door. The DMC also offers Activation & Event Grants for organisations looking to host their own events Downtown, and provides an Event Vendor Information pathway for businesses wanting to participate in DMC-organised events.</p>
                        <h3 class="globalThirdHeading" style="margin-top:4rem">The Data Advantage</h3>
                        <p class="globalText">Downtown Memphis currently has 31 projects under construction, 27 in the planning phase, and 39 recently completed, with a daytime population of 72,000 and 26,000 Downtown residents. The DMC makes all of this data publicly available through their Downtown Data Room and Downtown Dashboard, giving entrepreneurs powerful market intelligence before making location and investment decisions.</p>`,
    ctaOneText : "Thinking about bringing your business Downtown? The Downtown Memphis Commission offers grants, development programs, and resources to help entrepreneurs turn their vision into reality in the heart of Memphis. Explore everything they have to offer.",
    ctaOneButton : 'Learn More',
    ctaOneLink : 'https://downtownmemphis.com/',
    ctaTwoText : "New to Downtown Memphis? You may qualify for up to $45,000 in grant funding to help build out your space. Find out what incentives are available and start your application today.",
    ctaTwoButton : "Start Your Application",
    ctaTwoLink : 'https://downtownmemphis.com/develop-and-invest'
}