type offeringProp = {
    offerName : string,
    offerType : string,
    offerColor : string
}

export interface ResourcesType {
    id : string,
    mainImage : string,
    mainImageWidth : number,
    mainImageHeight : number,
    logo : string,
    logoWidth : number,
    logoHeight : number,
    articleTitle : string,
    blogTitle : string,
    readPath : string,
    description : string,
    offerings : offeringProp[],
    serveStage : string[],
    mainCategory : string,
    filterCategory : string[],
    subCategory : string[],
    introHeading : string,
    introParagraph : string,
    whosHeading : string,
    whosParagraph : string,
    whosImage : string,
    whosImagealt : string,
    whosImageWidth : number,
    whosImageHeight : number,
    offerBlockHeading : string,
    offerBlockText : string,
    ctaOneText : string,
    ctaOneButton : string,
    ctaOneLink : string,
    ctaTwoText : string,
    ctaTwoButton : string,
    ctaTwoLink : string
}