export const fairHousing = {
    memberStatus: true,
    id : "fair-housing-council-of-metropolitan-memphis",
    businessName : "Fair Housing Council of Metropolitan Memphis",
    bannerImage : "",
    profileLogo : "fair-housing-council-of-metropolitan-memphis",
    profileDescription : "The Fair Housing Council of Metropolitan Memphis (FHCMM) is a nonprofit fighting housing discrimination through education, enforcement, advocacy, and outreach. They support communities with training, fair housing testing, research, and resources for inclusive and equitable living.",
    profileCategory : [
        "community-government-non-profits",
    ],
    profileSubCategory : [
        "ngo-charities",
        "economic-workforce-development",
        "municipal-serives-community-projects",
        "housing-advocacy-fair-housing-services",
    ],
    profileBusinessDescription : ``,
    gallery : [{image : "", alt : ""}],
    businessHours : {
        monHours : "9am - 5pm",
        tueHours : "9am - 5pm",
        wedHours : "9am - 5pm",
        thuHours : "9am - 5pm",
        friHours : "9am - 5pm",
        satHours : "Closed",
        sunHours : "Closed"
    },
    addressLink : "https://share.google/5RtBATWe75S3OeohL",
    address : "3355 Poplar Ave #112, Memphis, TN 38111, United States",
    email : "chenise.anthony@fhcmm.org",
    website : "https://fhcmm.org/",
    telNumber : "9015387700",
    facebook : "",
    instagram : "http://www.instagram.com/metromemphis_fairhousing",
    youtube : "",
    linkedIn : "",
    linktree : "",
    twitter: "",
    tiktok : "",
    pinterest : ""
}