export const intellibyteSoftwareSolutions = {
    memberStatus: true,
    id : "intellibyte-software-solutions",
    businessName : "Intellibyte Software Solutions",
    bannerImage : "",
    profileLogo : "intellibyte",
    profileDescription : "IntelliByte Software Solutions delivers custom software, high-performance websites, and 24/7 help-desk support—helping businesses reduce costs and boost productivity through responsive, maintainable, and optimized digital solutions.",
    profileCategory : [
        "technology-communications",
        "marketing-advertising-media",
    ],
    profileSubCategory : [
        "web-app-development",
        "it-support-software-development",
        "website-design-development",
    ],
    profileBusinessDescription : ``,
    gallery : [{image : "", alt : ""}],
    businessHours : {
        monHours : "",
        tueHours : "",
        wedHours : "",
        thuHours : "",
        friHours : "",
        satHours : "",
        sunHours : ""
    },
    addressLink : "",
    address : "",
    email : "robert@intellibyte.dev",
    website : "https://intellibytesoftwaresolutions.com/",
    telNumber : "9018006754",
    facebook : "",
    instagram : "",
    youtube : "",
    linkedIn : "",
    linktree : "",
    twitter: "",
    tiktok : "",
    pinterest : ""
}