import { MembersListType } from './../membersListType'

export const neatNtidy : MembersListType = {
    memberStatus: false,
    id : "neat-n-tidy-cleaning-services",
    businessName : "Neat N Tidy Cleaning Services",
    bannerImage : "",
    profileLogo : "neatntidy",
    profileDescription : "Neat N Tidy Cleaning Services, LLC is a Memphis-based residential and light commercial cleaning company offering reliable, detail-focused cleaning solutions tailored to busy households and small businesses.",
    profileCategory : [
        "construction-home-improvement-trade-services",
    ],
    profileSubCategory : [
        "janitorial-services",
    ],
    categoryTag: [
        "house cleaning services",
        "residential cleaning services",
        "deep cleaning services",
        "move in cleaning",
        "move out cleaning",
        "office cleaning",
        "post event cleaning",
        "maid services",
        "home organisation",
        "decluttering",
        "sanitisation",
        "hygiene services",
    ],
    profileBusinessDescription : ``,
    gallery : [],
    businessHours : [
        { day : "Monday", hours : '9am - 4pm'},
        { day : "Tuesday", hours : '9am - 4pm'},
        { day : "Wednesday", hours : '9am - 4pm'},
        { day : "Thursday", hours : 'Closed'},
        { day : "Friday", hours : '9am - 4pm'},
        { day : "Saturday", hours : '9am - 12pm'},
        { day : "Sunday", hours : 'Closed'},
    ],
    addressLink : "https://share.google/28Iy2UVJUDlJGlEF8",
    address : "Memphis",
    email : "neatntidy2022@gmail.com",
    website : "https://gohere.online/neatntidymemphis/",
    telNumber : "901-979-1138",
    facebook : "https://www.facebook.com/NeatnTidyMemphis",
    instagram : "https://www.instagram.com/neat_n_tidy_llc/",
    youtube : "",
    linkedIn : "",
    linktree : "",
    twitter: "",
    tiktok : "",
    pinterest : ""
}