export const abramResidentialCleaning = {
    memberStatus: false,
    id : "abram-residential-commercial-cleaning",
    businessName : "Abram's Residential and Commercial Cleaning",
    bannerImage : "",
    profileLogo : "Black-chamber-of-Memphis",
    profileDescription : "Abram’s Residential and Commercial Cleaning offers professional cleaning services in Southaven, MS, serving both homes and businesses with reliable, detail-oriented care—including residential cleans, commercial space maintenance, and ironing services.",
    profileCategory : "home-property-construction",
    profileSubCategory : [
        "cleaning-maintenance-renovations",
    ],
    profileBusinessDescription : ``,
    gallery : [],
    businessHours : {
        monHours : "",
        tueHours : "",
        wedHours : "",
        thuHours : "",
        friHours : "",
        satHours : "",
        sunHours : ""
    },
    addressLink : "",
    address : "",
    email : "shainekaabram@gmail.com",
    website : "https://abrams-cleaning.ueniweb.com/",
    telNumber : "6628747328",
    facebook : "",
    instagram : "",
    youtube : "",
    linkedIn : "",
    linktree : "",
    twitter: "",
    tiktok : "",
    pinterest : ""
}