export const abrFirm = {
    id : "abr-firm",
    businessName : "ABR Firm",
    bannerImage : "",
    profileLogo : "abr-firm",
    profileDescription : "ABR FIRM is a Memphis-based consulting agency offering leadership development, team coaching, and brand strategy to nonprofits, small businesses, and ministries—fueling growth through customized, capacity-building partnerships.",
    profileCategory : [
        "business-finance-professional-services",
        "education-training-youth-development",
    ],
    profileSubCategory : [
        "business-consulting-coaching",
        "skills-development-training-centres",
        "personal-development-coacing",
    ],
    profileBusinessDescription : ``,
    gallery : [],
    businessHours : {
        monHours : "10am - 5pm",
        tueHours : "9am - 5pm",
        wedHours : "9am - 5pm",
        thuHours : "9am - 5pm",
        friHours : "9am - 1pm",
        satHours : "Closed",
        sunHours : "Closed"
    },
    addressLink : "https://maps.app.goo.gl/UeuuCnbrScNqgJM5A",
    address : "923 Parkrose Rd, Memphis, TN 38109",
    email : "better@abrfirmmemphis.com",
    website : "https://www.abrfirmmemphis.com/",
    telNumber : "9015583249",
    facebook : "",
    instagram : "",
    youtube : "https://www.youtube.com/channel/UC0_qfSVVYGKCFx6I0Gcyydg",
    linkedIn : "http://www.linkedin.com/in/reneelee-abrfirm",
    linktree : "",
    twitter: "",
    tiktok : "",
    pinterest : ""
}