export const absbResources = {
    memberStatus: false,
    id : "absb-resources",
    businessName : "ABSB Resources",
    bannerImage : "",
    profileLogo : "absb-resources",
    profileDescription : "ABSB Resources (dba CaissaK12 Communications LLC) is a Memphis-based strategic communications and K–12 enrollment consultancy that helps public school districts recruit new students, reduce chronic absenteeism, and improve parent engagement using data-driven campaigns and software solutions.",
    profileCategory : "education-training-youth-development",
    profileSubCategory : [],
    profileBusinessDescription : ``,
    gallery : [],
    businessHours : {
        monHours : "",
        tueHours : "",
        wedHours : "",
        thuHours : "",
        friHours : "",
        satHours : "",
        sunHours : ""
    },
    addressLink : "",
    address : "",
    email : "absbresources@att.net",
    website : "https://www.absbresources.com/",
    telNumber : "",
    facebook : "https://www.facebook.com/Caissak12",
    instagram : "https://www.instagram.com/caissak12/",
    youtube : "https://www.youtube.com/channel/UCOqA8faa5PCqhNC-VDgwvgw",
    linkedIn : "https://www.linkedin.com/company/caissa-public-strategy/",
    linktree : "",
    twitter: "",
    tiktok : "",
    pinterest : ""
}