export const actionChem = {
    memberStatus: false,
    id : "action-janitorial-paper-safety",
    businessName : "Action Janitorial Paper Safety (Action JPS)",
    bannerImage : "",
    profileLogo : "action",
    profileDescription : "Action Janitorial Paper Safety (Action JPS) is a Memphis-based distributor of janitorial chemicals, cleaning equipment, paper products, PPE, and disposables. Serving businesses and organizations since 1994, they offer reliable, one-stop facility supply solutions for janitorial, safety, and food service needs.",
    profileCategory : [
        "industrial-engineering-manufacturing",
        "home-property-construction",
        "retail-shopping-consumer-goods",
    ],
    profileSubCategory : [
        "industrial-supplies",
        "cleaning-maintenance-renovations",
        "construction-building-services",
        "janitorial-safety-facility-supply-distribution",
    ],
    profileBusinessDescription : ``,
    gallery : [{image : "", alt : ""}],
    businessHours : {
        monHours : "8am - 4:30pm",
        tueHours : "8am - 4:30pm",
        wedHours : "8am - 4:30pm",
        thuHours : "8am - 4:30pm",
        friHours : "8am - 4pm",
        satHours : "Closed",
        sunHours : "Closed"
    },
    addressLink : "https://share.google/kV7SbWbJL8soh2O9h",
    address : "275 Cumberland St., Memphis, TN, 38112",
    email : "charles@actionjps.com",
    website : "https://actionjps.com/",
    telNumber : "",
    facebook : "",
    instagram : "",
    youtube : "",
    linkedIn : "https://www.linkedin.com/in/dina-wright-brown-b04849116",
    linktree : "",
    twitter: "",
    tiktok : "",
    pinterest : ""
}