export const agapeChildFamilyServices = {
    memberStatus: false,
    id : "agape-child-family-services",
    businessName : "Agape Child and Family Services",
    bannerImage : "",
    profileLogo : "agape",
    profileDescription : "Agape Child & Family Services is a faith-based nonprofit in Memphis offering adoption, foster care prevention, counseling, homelessness support, workforce readiness, educational programs, and spiritual care to under-resourced families.",
    profileCategory : [
        "community-government-non-profits",
        "health-wellness-personal-care",
    ],
    profileSubCategory : [
        "ngo-charities",
        "mental-health-services",
        "religion-faith-based-groups",
        "economic-workforce-development",
        "emergency-servies",
        "family-youth-community-support-services",
    ],
    profileBusinessDescription : ``,
    gallery : [{image : "", alt : ""}],
    businessHours : {
        monHours : "",
        tueHours : "",
        wedHours : "",
        thuHours : "",
        friHours : "",
        satHours : "",
        sunHours : ""
    },
    addressLink : "https://g.co/kgs/BJQUduM",
    address : "3160 Directors Row, Memphis, Tn, 38131",
    email : "info@agapemeanslove.org",
    website : "http://agapemeanslove.org/",
    telNumber : "",
    facebook : "https://www.facebook.com/AgapeMeansLove",
    instagram : "",
    youtube : "https://www.youtube.com/user/AgapeMeanslovenow",
    linkedIn : "https://www.linkedin.com/company/agapechildandfamilyservices",
    linktree : "",
    twitter: "https://twitter.com/agapemeanslove",
    tiktok : "",
    pinterest : ""
}