export const tourOfPossibilities = {
    memberStatus: false,
    id : "tour-of-possibilities",
    businessName : "A Tour Of Possibilities",
    bannerImage : "",
    profileLogo : "a-tour-of-possibilities",
    profileDescription : "A Tour of Possibilities (ATOP Memphis) leads powerful African American heritage tours across historic Memphis—public, private, virtual, and culinary formats—celebrating culture, civil rights history, and local identity.",
    profileCategory : "automotive-transport-travel-tours",
    profileSubCategory : [
        "travel-agencies-tours-tourist-activities",
    ],
    profileBusinessDescription : ``,
    gallery : [],
    businessHours : {
        monHours : "",
        tueHours : "",
        wedHours : "",
        thuHours : "",
        friHours : "",
        satHours : "",
        sunHours : ""
    },
    addressLink : "https://maps.app.goo.gl/WBtNEoLE7dDtgxF58",
    address : "119 Riverside Dr, Memphis, TN 38103",
    email : "atopmemphiscmb@gmail.com",
    website : "http://www.atopmemphis.com/",
    telNumber : "9013263736",
    facebook : "http://www.facebook.com/atopmemphis",
    instagram : "http://www.instagram.com/atopmemphis",
    youtube : "https://www.youtube.com/channel/UCbsPyf2w32XGg5e1UZmIxRA",
    linkedIn : "http://www.linkedin.com/in/carolyn-michael-banks-53ba4b43",
    linktree : "",
    twitter: "",
    tiktok : "",
    pinterest : ""
}