export const expressWages = {
    memberStatus: true,
    id : "express-wages",
    businessName : "Express Wages",
    bannerImage : "",
    profileLogo : "express-wages",
    profileDescription : "Express Wages is a fintech payroll services company in Memphis offering on-demand earned wage access (EWA), allowing hourly and wage workers to access their earned pay instantly or by the next day.",
    profileCategory : [
        "business-finance-professional-services",
    ],
    profileSubCategory : [
        "accounting-financial-services",
        "admin-hr-recruitment",
        "workforce-development-training",
    ],
    profileBusinessDescription : ``,
    gallery : [{image : "", alt : ""}],
    businessHours : {
        monHours : "",
        tueHours : "",
        wedHours : "",
        thuHours : "",
        friHours : "",
        satHours : "",
        sunHours : ""
    },
    addressLink : "",
    address : "",
    email : "alfredm@expresswages.com",
    website : "https://expresswages.com/",
    telNumber : "9015939199",
    facebook : "https://www.facebook.com/expresswages",
    instagram : "https://www.instagram.com/expresswages/",
    youtube : "https://www.youtube.com/@ExpressWages",
    linkedIn : "https://www.linkedin.com/company/express-wages",
    linktree : "",
    twitter: "https://twitter.com/ExpressWages",
    tiktok : "",
    pinterest : ""
}