export const brighterDaysNites = {
    memberStatus: true,
    id : "brighter-days-nites",
    businessName : "Brighter Days & Nites",
    bannerImage : "",
    profileLogo : "Black-chamber-of-Memphis",
    profileDescription : "Brighter Days & Nites, Inc. is a Memphis-based, minority/woman-owned electrical and industrial supplier supplying lighting, wiring, fixtures and related products to contractors, utilities, government agencies, and institutions—serving clients with quality, variety, and competitive pricing.",
    profileCategory : [
        "industrial-engineering-manufacturing",
        "home-property-construction",
        "business-finance-professional-services",
        "retail-shopping-consumer-goods",
    ],
    profileSubCategory : [
        "industrial-supplies",
        "machinery-equipment",
        "construction-building-services",
        "construction-compliance-government-contract-support",
        "electrical-lighting-supplies-wholesalers",
    ],
    profileBusinessDescription : ``,
    gallery : [{image : "", alt : ""}],
    businessHours : {
        monHours : "",
        tueHours : "",
        wedHours : "",
        thuHours : "",
        friHours : "",
        satHours : "",
        sunHours : ""
    },
    addressLink : "",
    address : "2165 Troyer Ave, Memphis, TN 38114",
    email : "dlsinclair@bdnincorp.com",
    website : "http://www.bdnincorp.com",
    telNumber : "9017751902",
    facebook : "",
    instagram : "",
    youtube : "",
    linkedIn : "https://www.linkedin.com/company/brighter-days-&-nites-inc",
    linktree : "",
    twitter: "",
    tiktok : "",
    pinterest : ""
}