export const wakilProImage = {
    id : "wakil-pro-image",
    businessName : "Wakil Pro Image",
    bannerImage : "",
    profileLogo : "wakil-pro-image",
    profileDescription : "Wakil Solutions offers custom screen printing, apparel branding, signage, and promotional graphics in Memphis — turning your design into lasting impressions.",
    profileCategory : [
        "marketing-advertising-media",
        "retail-shopping-consumer-goods",
    ],
    profileSubCategory : [
        "branded-merchandise",
        "graphic-design",
        "branding-visual-identity",
        "marketing-material-print-media",
    ],
    profileBusinessDescription : ``,
    gallery : [],
    businessHours : {
        monHours : "9am - 5pm",
        tueHours : "9am - 5pm",
        wedHours : "9am - 5pm",
        thuHours : "9am - 5pm",
        friHours : "9am - 5pm",
        satHours : "Closed",
        sunHours : "Closed"
    },
    addressLink : "https://share.google/abBJUIQcfGG4wrobe",
    address : "Memphis",
    email : "sales@wakilproimage.com",
    website : "https://wakilsolutions.com/",
    telNumber : "9012758445",
    facebook : "https://www.facebook.com/AncoraThemes/",
    instagram : "https://www.instagram.com/ancora_themes/",
    youtube : "",
    linkedIn : "",
    linktree : "",
    twitter: "https://twitter.com/ancora_themes",
    tiktok : "",
    pinterest : ""
}