export const wakilProImage = {
    memberStatus: false,
    id : "wakil-pro-image",
    businessName : "Wakil Pro Image",
    bannerImage : "",
    profileLogo : "wakil-pro-image",
    profileDescription : "Wakil Solutions offers custom screen printing, apparel branding, signage, and promotional graphics in Memphis — turning your design into lasting impressions.",
    profileCategory: [
        "retail-shopping-specialty-stores",
        "marketing-advertising-digital-services",
    ],
    profileSubCategory: [
        "brand-strategy",
        "graphic-design"
    ],
    categoryTag: [
        "branded merchandise",
        "custom printing",
        "business cards printing",
        "banner printing",
        "flyers & brochures printing",
        "custom T-shirt printing",
        "graphic design services",
        "promotional merchandise",
        "branded merchandise",
        "poster printing",
        "print shop Memphis",
        "signs and banners",
        "marketing materials printing",
    ],
    profileBusinessDescription : ``,
    gallery : [],
    businessHours : {
        monHours : "9am - 5pm",
        tueHours : "9am - 5pm",
        wedHours : "9am - 5pm",
        thuHours : "9am - 5pm",
        friHours : "9am - 5pm",
        satHours : "Closed",
        sunHours : "Closed"
    },
    addressLink : "https://share.google/abBJUIQcfGG4wrobe",
    address : "Memphis",
    email : "sales@wakilproimage.com",
    website : "https://wakilsolutions.com/",
    telNumber : "9012758445",
    facebook : "https://www.facebook.com/AncoraThemes/",
    instagram : "https://www.instagram.com/ancora_themes/",
    youtube : "",
    linkedIn : "",
    linktree : "",
    twitter: "https://twitter.com/ancora_themes",
    tiktok : "",
    pinterest : ""
}