import { MembersListType } from './../membersListType'

export const walkerWarrenCommunications : MembersListType = {
    memberStatus: false,
    id : "walker-warren-communications",
    businessName : "Walker Warren Communications",
    bannerImage : "",
    profileLogo : "walker-warren-communications",
    profileDescription : "WW911 provides 911 dispatch, GIS & emergency communications services for Wichita and Wilbarger counties in Texas, ensuring swift, coordinated responses.",
    profileCategory: [
        "community-faith-nonprofit-services",
    ],
    profileSubCategory: [
        "emergency-services",
        "cpr",
    ],
    categoryTag: [
        "911 emergency dispatch",
        "emergency communications",
        "public safety services",
        "911 call center",
        "emergency response coordination",
        "county emergency services",
        "first responder communications",
    ],
    profileBusinessDescription : ``,
    gallery : [],
    businessHours : [
        { day : "Monday", hours : "24 hours",},
        { day : "Tuesday", hours : "24 hours",},
        { day : "Wednesday", hours : "24 hours",},
        { day : "Thursday", hours : "24 hours", },
        { day : "Friday", hours : "24 hours", },
        { day : "Saturday", hours :"24 hours", },
        { day : "Sunday", hours : "24 hours"},
    ],
    addressLink : "https://share.google/2roL2s7OAp0koMPZK",
    address : "155 S Mendenhall Rd, Memphis, TN 38117",
    email : "carol@ww911.net",
    website : "https://ww911.net/",
    telNumber : "901-337-6326",
    facebook : "",
    instagram : "",
    youtube : "",
    linkedIn : "",
    linktree : "",
    twitter: "",
    tiktok : "",
    pinterest : ""
}