export const wrightNow = {
    memberStatus: false,
    id : "wright-now",
    businessName : "Wright Now",
    bannerImage : "",
    profileLogo : "Black-chamber-of-Memphis",
    profileDescription : "Wright Now, LLC is a Memphis-based minority- and women-owned consulting and staffing firm specializing in workforce development, apprenticeship programs, HR support, and small business strategy.",
    profileCategory : [
        "education-training-youth-development",
        "business-finance-professional-services",
    ],
    profileSubCategory : [
        "professional-development-leadership-workforce-training",
        "admin-hr-recruitment",
        "workforce-development-training",
    ],
    profileBusinessDescription : ``,
    gallery : [],
    businessHours : {
        monHours : "",
        tueHours : "",
        wedHours : "",
        thuHours : "",
        friHours : "",
        satHours : "",
        sunHours : ""
    },
    addressLink : "",
    address : "8498 Kamin Ln, Memphis, Tn 38125",
    email : "laquitawright40@gmail.com",
    website : "https://wrightnowllc.com/",
    telNumber : "9016129898",
    facebook : "",
    instagram : "",
    youtube : "",
    linkedIn : "",
    linktree : "",
    twitter: "",
    tiktok : "",
    pinterest : ""
}