export const youFirstComFoundation = {
    memberStatus: false,
    id : "you-first-community-foundation",
    businessName : "You First Community Foundation",
    bannerImage : "",
    profileLogo : "Black-chamber-of-Memphis",
    profileDescription : "You First Community Foundation is a Memphis-based nonprofit empowering women, girls, and justice-impacted youth through menstrual equity, reentry support, mentorship, and career-skills programs.",
    profileCategory : [
        "community-government-non-profits",
        "education-training-youth-development",
    ],
    profileSubCategory : [
        "ngo-charities",
        "youth-programs-tutoring",
        "professional-development-leadership-workforce-training",
    ],
    profileBusinessDescription : ``,
    gallery : [],
    businessHours : {
        monHours : "",
        tueHours : "",
        wedHours : "",
        thuHours : "",
        friHours : "",
        satHours : "",
        sunHours : ""
    },
    addressLink : "",
    address : "",
    email : "info@youfirstcf.org",
    website : "https://youfirstcf.org/",
    telNumber : "9012497281",
    facebook : "https://www.facebook.com/youfirstcf/",
    instagram : "https://www.instagram.com/youfirstcf/",
    youtube : "",
    linkedIn : "https://www.linkedin.com/company/youfirstcf",
    linktree : "",
    twitter: "",
    tiktok : "",
    pinterest : ""
}