export const yourPersonalChef = {
    memberStatus: false,
    id : "your-personal-chef-carolas-catering",
    businessName : "Your Personal Chef! - Carolas Catering",
    bannerImage : "",
    profileLogo : "yourpersonalchef",
    profileDescription : "Your Personal Chef (by Carolyn Rudgley) brings Memphis wholesome, from-scratch meals—through weekly preps, grab-and-bake kits, catered events, and interactive cooking classes for adults and kids—with dependable, affordable, and home-style flavor.",
    profileCategory : [
        "food-drinks-hospitality",
        "retail-shopping-consumer-goods",
        "education-training-youth-development",
        "event-arts-entertainment",
    ],
    profileSubCategory : [
        "bakeries-catering-event-food-services",
        "farmers-market-vendor",
        "arts-crafts-creative-workshops",
        "event-catering-concession-services",
    ],
    profileBusinessDescription : ``,
    gallery : [{image : "", alt : ""}],
    businessHours : {
        monHours : "",
        tueHours : "",
        wedHours : "",
        thuHours : "",
        friHours : "",
        satHours : "",
        sunHours : ""
    },
    addressLink : "",
    address : "",
    email : "carolscatering@comcast.net",
    website : "https://www.your-personal-chef.com/",
    telNumber : "9012689951",
    facebook : "https://www.facebook.com/YourPersonalChefCarolyn",
    instagram : "https://www.instagram.com/yourpersonalchef1/",
    youtube : "",
    linkedIn : "",
    linktree : "",
    twitter: "",
    tiktok : "",
    pinterest : ""
}