import { SocialLink } from "./blackLedgerLinkProp";

export interface BlackLedgerProp {
    id : string,
    backgroundImage : string,
    businessTitle : string,
    socialLinks: SocialLink[],
    headingOne : string,
    answerOne : string,
    headingTwo : string,
    answerTwo : string,
    headingThree : string,
    answerThree : string,
    headingFour : string,
    answerFour : string,
    headingFive : string,
    answerFive : string,
    headingSix : string,
    answerSix : string,
    headingSeven : string,
    answerSeven : string,
    endBlockText : string,
    imageOne : string,
    imageOneAlt : string,
    imageTwo : string,
    imageTwoAlt : string,
    imageThree : string,
    imageThreeAlt : string,
    imageFour : string,
    imageFourAlt : string,
    imageFive : string,
    imageFiveAlt : string,
    imageSix : string,
    imageSixAlt : string,
    videoLink : { isVideoTrue : boolean, videoPath : string, videoTitle : string}[],
}