export interface BlackLedgerProp {
    id : string,
    backgroundImage : string,
    businessTitle : string,
    // socialLinks: {icon: Element; href: string}[],
    answerOne : string,
    answerTwo : string,
    answerThree : string,
    answerFour : string,
    answerFive : string,
    imageOne : string,
    imageOneAlt : string,
    imageTwo : string,
    imageTwoAlt : string,
    imageThree : string,
    imageThreeAlt : string,
    imageFour : string,
    imageFourAlt : string,
    imageFive : string,
    imageFiveAlt : string,
}