export const theBlackPearlNailAcademy = {
    memberStatus: false,
    id : "the-black-pearl-nail-academy",
    businessName : "The Black Pearl Nail Academy",
    bannerImage : "",
    profileLogo : "the-black-pearl-nail-academy",
    profileDescription : "The Black Pearl Nail Academy is Tennessee’s only specialty manicure school in Memphis, offering hybrid, traditional, apprenticeship, instructor, and refresher programs that prepare students for licensure and careers in the nail industry.",
    profileCategory : [
        "health-wellness-personal-care",
        "education-training-youth-development",
    ],
    profileSubCategory : [
        "beauty-hair-spa-services",
        "nail-technician-training-certification",
    ],
    profileBusinessDescription : ``,
    gallery : [{image : "", alt : ""}],
    businessHours : {
        monHours : "",
        tueHours : "",
        wedHours : "",
        thuHours : "",
        friHours : "",
        satHours : "",
        sunHours : ""
    },
    addressLink : "",
    address : "1012 East Raines Road, Memphis, Tn 38116",
    email : "theblackpearlnailacademy@gmail.com",
    website : "https://www.theblackpearlnailacademy.com/",
    telNumber : "9012922966",
    facebook : "https://www.facebook.com/BLACKPEARLNAILACADEMY",
    instagram : "https://www.instagram.com/theblackpearlnailacademy/",
    youtube : "",
    linkedIn : "",
    linktree : "",
    twitter: "",
    tiktok : "https://www.tiktok.com/@tbpna",
    pinterest : ""
}