export const theM9Eats = {
    memberStatus: false,
    id : "the-m9-eats",
    businessName : "The M9 Eats",
    bannerImage : "",
    profileLogo : "the-m9-eats",
    profileDescription : "The M9 Eats is a Memphis culinary brand offering locally made BBQ sauces, specialty seasonings, and flavorful ready-to-eat meals—rooted in family recipes and sold at area markets.",
    profileCategory : [
        "food-drinks-hospitality",
        "retail-shopping-consumer-goods",
    ],
    profileSubCategory : [
        "bakeries-catering-event-food-services",
        "farmers-market-vendor",
        "specialty-food-gourmet-products",
    ],
    profileBusinessDescription : ``,
    gallery : [],
    businessHours : {
        monHours : "",
        tueHours : "",
        wedHours : "",
        thuHours : "",
        friHours : "",
        satHours : "",
        sunHours : ""
    },
    addressLink : "https://g.co/kgs/bjwEoUH",
    address : "1249 Heistan Place, Memphis, TN 38104",
    email : "them9memphis@yahoo.com",
    website : "https://www.them9eats.com/",
    telNumber : "9013154335",
    facebook : "https://www.facebook.com/The-M9-101924425899058/",
    instagram : "https://www.instagram.com/The_m9_memphis",
    youtube : "",
    linkedIn : "",
    linktree : "",
    twitter: "",
    tiktok : "",
    pinterest : ""
}