export const theRedwingGroup = {
    id : "the-redwing-group",
    businessName : "The Redwing Group",
    bannerImage : "",
    profileLogo : "the-redwing-group",
    profileDescription : "The Redwing Group, LLC (TRG) is a Memphis-based public strategies firm specializing in government relations, strategic communications, business development, and community outreach.",
    profileCategory : [
        "community-government-non-profits",
        "business-finance-professional-services",
    ],
    profileSubCategory : [
        "municipal-serives-community-projects",
        "business-consulting-coaching",
        "strategic-planning-organizational-development",
    ],
    profileBusinessDescription : ``,
    gallery : [],
    businessHours : {
        monHours : "8am - 5pm",
        tueHours : "8am - 5pm",
        wedHours : "8am - 5pm",
        thuHours : "8am - 5pm",
        friHours : "8am - 5pm",
        satHours : "8am - 5pm",
        sunHours : "8am - 5pm"
    },
    addressLink : "https://g.co/kgs/BJPTP8D",
    address : "40 S Main St Suite 2150, Memphis, TN 38103",
    email : "ron.redwing@theredwinggroup.com",
    website : "https://theredwinggroup.com/",
    telNumber : "9013125560",
    facebook : "https://www.facebook.com/RedwingPublicStrategies/",
    instagram : "https://www.instagram.com/the_redwing_group/",
    youtube : "",
    linkedIn : "https://www.linkedin.com/company/theredwinggroup/%20",
    linktree : "",
    twitter: "https://twitter.com/theredwinggroup",
    tiktok : "",
    pinterest : ""
}