export const theResumeReviveCareerServ = {
    memberStatus: false,
    id : "the-resume-revive-career-services",
    businessName : "The Resume Revive Career Services",
    bannerImage : "",
    profileLogo : "the-resume-revive-career-service",
    profileDescription : "The Resume Revive Career Services provides Memphis-based professionals with bespoke resume writing, career coaching, outplacement support, and strategic job-search tools to accelerate career growth.",
    profileCategory : [
        "business-finance-professional-services",
        "education-training-youth-development",
    ],
    profileSubCategory : [
        "professional-resume-writing",
        "personal-development-coacing",
        "education-software-saas-solutions",
        "professional-development-leadership-workforce-training",
    ],
    profileBusinessDescription : ``,
    gallery : [],
    businessHours : {
        monHours : "",
        tueHours : "",
        wedHours : "",
        thuHours : "",
        friHours : "",
        satHours : "",
        sunHours : ""
    },
    addressLink : "https://g.co/kgs/pK8XD7x",
    address : "5104 Autumn Morning Lane, Memphis, Tn, 38125",
    email : "kameke@theresumerevive.com",
    website : "https://www.theresumerevive.com/",
    telNumber : "9016792716",
    facebook : "https://www.facebook.com/Theresumerevive/",
    instagram : "",
    youtube : "",
    linkedIn : "https://www.linkedin.com/company/the-resume-revive-career-services",
    linktree : "",
    twitter: "",
    tiktok : "",
    pinterest : ""
}