export const thrivent = {
    id : "thrivent",
    businessName : "Thrivent",
    bannerImage : "",
    profileLogo : "",
    profileDescription : "",
    profileCategory : [],
    profileSubCategory : [],
    profileBusinessDescription : ``,
    gallery : [{image : "", alt : ""}],
    businessHours : {
        monHours : "",
        tueHours : "",
        wedHours : "",
        thuHours : "",
        friHours : "",
        satHours : "",
        sunHours : ""
    },
    addressLink : "",
    address : "",
    email : "",
    website : "",
    telNumber : "",
    facebook : "",
    instagram : "",
    youtube : "",
    linkedIn : "",
    linktree : "",
    twitter: "",
    tiktok : "",
    pinterest : ""
}