export const trustMarketingComs = {
    memberStatus: false,
    id : "trust-marketing-communications",
    businessName : "Trust Marketing & Communications",
    bannerImage : "",
    profileLogo : "trust-marketing-communications",
    profileDescription : "Trust Marketing & Communications is a Downtown Memphis PR and marketing powerhouse offering full-spectrum strategy, media production, and research, backed by deep community impact and award-winning leadership.",
    profileCategory : [
        "marketing-advertising-media",
    ],
    profileSubCategory : [
        "voiceover-audio-production-services",
        "radio-tv-show-development",
        "video-production-multimedia",
    ],
    profileBusinessDescription : ``,
    gallery : [],
    businessHours : {
        monHours : "8:30am - 5pm",
        tueHours : "8:30am - 5pm",
        wedHours : "8:30am - 5pm",
        thuHours : "8:30am - 5pm",
        friHours : "8:30am - 5pm",
        satHours : "Closed",
        sunHours : "Closed"
    },
    addressLink : "https://g.co/kgs/9uX9pxU",
    address : "65 Union Ave Suite 300, Memphis, TN 38103",
    email : "trusthoward@gmail.com",
    website : "https://trustmkt.com/",
    telNumber : "9015211300",
    facebook : "https://www.facebook.com/trustmktcommunications/",
    instagram : "",
    youtube : "",
    linkedIn : "https://www.linkedin.com/company/trust-marketing-communications/posts/?feedView-all",
    linktree : "",
    twitter: "",
    tiktok : "",
    pinterest : ""
}