import { MembersListType } from './../membersListType'

export const cushionEmployerServices : MembersListType = {
    memberStatus: false,
    id : "cushion-employer-services-corp",
    businessName : "Cushion Employer Services Corp",
    bannerImage : "",
    profileLogo : "cushion",
    profileDescription : "Cushion Employer Services Nashville TN, HR consulting Nashville, workforce solutions Tennessee, human resources outsourcing Nashville, benefits administration Nashville, employer screening Nashville, compensation strategy Nashville HR, performance management TN, talent acquisition Nashville, compliance HR Nashville",
    profileCategory : [
        "professional-legal-financial-services",
    ],
    profileSubCategory : [
        "succession-planning-solutions",
        "business-consultants",
    ],
    categoryTag: [
        "human resources consulting",
        "hr outsourcing",
        "benefits administration",
        'talent acquisition',
        "employee engagement",
        "culture building",
        'performance strategy',
        'compensation strategy',
        'employer screenign',
        'compliance solutions',
        'leadership development',
        "workforce solutions",
    ],
    profileBusinessDescription : ``,
    gallery : [],
    businessHours : [
        { day : "Monday", hours : '8am - 5:30pm'},
        { day : "Tuesday", hours : '8am - 5:30pm'},
        { day : "Wednesday", hours : '8am - 5:30pm'},
        { day : "Thursday", hours : '8am - 5:30pm'},
        { day : "Friday", hours : '8am - 5:30pm'},
        { day : "Saturday", hours : 'Closed'},
        { day : "Sunday", hours : 'Closed'},
    ],
    addressLink : "https://g.co/kgs/m857vBK",
    address : "1910 Church Street, Suite 200, Nashville, Tn 37203",
    email : "info@cushioncorp.com",
    website : "https://www.cushioncorp.com/",
    telNumber : "",
    facebook : "https://www.facebook.com/Cushion-Employer-Services-211484559416172/",
    instagram : "http://instagram.com/cushion_es",
    youtube : "",
    linkedIn : "https://www.linkedin.com/company/cushion-employer-services/",
    linktree : "",
    twitter: "https://twitter.com/CushionES",
    tiktok : "",
    pinterest : ""
}