import PageHeroSection from "@/components/heroSections/pageHeroSection";
import OneColumn from "@/components/WordImageBlocks/OneColumn";

import style from './farmtoTable.module.css'
import SingleCTAButton from "@/components/callToAction/SingleCTAButton";

export default function FarmToTable(){
    const heroBtnList = [
        {
            name : "Join the Table",
            path : '/programs/farm-to-table/application-form',
            type : 'globalGoldButton'
        }
    ]

    const cards = [
        {
            eventTopic : 'Strengthen the Food Supply Chain',
            eventDateTime : '',
            eventAddressLink : '',
            eventAddress : '',
            eventCtaButton : '',
            eventCtaLink : '',
            eventDetails : `</p>CCreate intentional relationships among growers, producers, suppliers, distributors, restaurants, retailers, institutions and buyers.</p>`,
        },{
            eventTopic : 'Build Stronger Businesses',
            eventDateTime : '',
            eventAddressLink : '',
            eventAddress : '',
            eventCtaButton : '',
            eventCtaLink : '',
            eventDetails : `<p>Connect businesses and their workforce to training, technical assistance and resources that strengthen operations and prepare them for growth.</p>`,
        },{
            eventTopic : 'Expand Access',
            eventDateTime : '',
            eventAddressLink : '',
            eventAddress : '',
            eventCtaButton : '',
            eventCtaLink : '',
            eventDetails : `<p>Increase visibility into sourcing, purchasing, procurement, partnership and business-development opportunities.</p>`,
        },{
            eventTopic : 'Create Pathways for Growth',
            eventDateTime : '',
            eventAddressLink : '',
            eventAddress : '',
            eventCtaButton : '',
            eventCtaLink : '',
            eventDetails : `<p>Help businesses explore packaged goods, wholesale, retail, hospitality and institutional markets.</p>`,
        }
    ]

    return(
        <main>
            <PageHeroSection
                eventHost = {'Black Chamber of Memphis'}
                mainHeading = {"Farm-to-Table Council"}
                subHeading = {'Strengthening the Local Food Economy'}
                heroParagraph = {`
                    <p>The Farm to Table Council connects Memphis-area food operators with industry training, resources, relationships, and opportunities to grow their businesses while strengthening the local food economy.</p>
                    <p>We are building a more connected food ecosystem where local businesses have greater access to relationships, resources, markets and opportunities—and clearer pathways to sustainable growth.</p>
                `}
                searchbar = {false}
                ctaButtons = {heroBtnList}
                placeholder = {''}
                initialSearchTerm = {''}
                eventDate = {''}
                eventTime = {''}
                eventPrice = {''}
                eventAddress = {''}
                stateButtons = {[]}
                selectedState = {''}
                setSelectedState = {undefined}
            />

            <OneColumn
                backgroundColor = {''}
                textColor = {''}
                headingIntro = {'WHY THE COUNCIL EXISTS'}
                headingTextColor = {''}
                blockHeading = {'One Food Economy. More Connections. Greater Opportunity.'}
                subHeading = {''}
                paragraph = {`
                    <p>Memphis has no shortage of talented food entrepreneurs, growers, makers and hospitality businesses. What is often missing is connection across the entire system.</p>
                    <ul>
                        <li>A restaurant may be looking for a dependable local supplier.</li>
                        <li>A farmer may need relationships with new buyers.</li>
                        <li>A food entrepreneur may be ready to move a product from the kitchen to retail shelves.</li>
                        <li>An institution may want to purchase locally but need a stronger pipeline of prepared vendors.</li>
                    </ul>
                    <p>The Farm-to-Table Council helps close those gaps.</p>
                    <p>Led by the Black Chamber of Memphis, the Council strengthens relationships across the food supply chain, connects businesses to growth resources and creates more opportunities for local businesses to participate in the economic activity generated by Memphis' food, hospitality and tourism industries.</p>
                    <p>This is bigger than food. It is about business growth, stronger supply chains, quality jobs and keeping more economic opportunities circulating within our region.</p>
                `}
                multiWeekProgram = {false}
                multiEvents = {[]}
                paragraphTwo = {''}
            />

            <section
                className={style.sectionTwo}
            >

                <h2
                    className="globalSecondHeading"
                >
                    The Full Food Economy Has a Seat at the Table
                </h2>

                <p
                    className="globalText"
                >
                    The Farm-to-Table Council brings together the people and organizations that grow it, make it, move it, serve it, sell it and purchase it. Our members represent different parts of the food economy but share one goal: building stronger businesses through stronger connections.
                </p>

                <h3 
                    className="globalThirdHeading"
                    style={{marginTop:"3rem"}}
                >
                    Businesses That Grow, Make & Serve
                </h3>

                <div
                    className={style.flipboxRow}
                >
                    <div
                        className={style.flipBox}
                    >
                        <h3
                            className={style.flipboxHeading}
                        >
                            Growers & Producers
                        </h3>
                        <p
                            className={style.flipboxText}
                        >
                            Farmers, urban growers, agricultural businesses, food manufacturers, bakers, beverage makers and other producers.
                        </p>
                    </div>

                    <div
                        className={style.flipBox}
                    >
                        <h3
                            className={style.flipboxHeading}
                        >
                            Food Entrepreneurs
                        </h3>
                        <p
                            className={style.flipboxText}
                        >
                            Restaurants, caterers, chefs, food trucks, mobile vendors, meal-preparation businesses and emerging food concepts.
                        </p>
                    </div>

                    <div
                        className={style.flipBox}
                    >
                        <h3
                            className={style.flipboxHeading}
                        >
                            Packaged Goods Brands
                        </h3>
                        <p
                            className={style.flipboxText}
                        >
                            Entrepreneurs developing sauces, seasonings, beverages, snacks, frozen products and other consumer packaged goods.
                        </p>
                    </div>

                    <div
                        className={style.flipBox}
                    >
                        <h3
                            className={style.flipboxHeading}
                        >
                            Suppliers & Distributors
                        </h3>
                        <p
                            className={style.flipboxText}
                        >
                            Food distributors, wholesalers, equipment and supply companies, cold-storage providers, logistics businesses and other supply-chain partners.
                        </p>
                    </div>
                </div>

                <ul
                    className="globalText"
                    style={{lineHeight:"1.5"}}
                >
                        <li>Open to startups, micro, small, established businesses, nonprofit food providers (e.g. community farmers markets/grocers), and corporations.</li>
                        <li>No minimum or maximum number of employees.</li>
                        <li>No minimum revenue requirement.</li>
                        <li>Business must be registered.</li>
                        <li>Business does not need to be located in Memphis — must be located within the Mid-South region.</li>
                        <li>Owner does not need to live in Memphis.</li>
                        <li>Open to both BCoM members and non-members.</li>
                        <li>No age requirement.</li>
                        <li>No other demographic requirements. Participants should have an existing business or be actively operating within the local food ecosystem.</li>
                    </ul>
                    <div 
                        style={{width:'90%', display:'flex', alignItems:'center', justifyContent:'center', background:'var(--grey)', padding:'2rem 0', margin:'4rem 0', borderRadius:'20px'}}
                    >
                        <p 
                            className="globalText"
                            style={{color:"#000000"}}
                        >
                            This program is designed for food and hospitality business owners who are looking to build industry connections, access training and resources, and identify opportunities to grow and strengthen their businesses.
                        </p>
                    </div>
            </section>

            <OneColumn
                backgroundColor = {'var(--black)'}
                textColor = {'var(--white)'}
                headingIntro = {''}
                headingTextColor = {''}
                blockHeading = {'Four ways we strengthen the local food economy.'} 
                subHeading = {''}
                paragraph = {`
                    
                `}
                multiWeekProgram = {true}
                multiEvents = {cards}
                paragraphTwo = {``}
            />

            <OneColumn
                backgroundColor = {'var(--white)'}
                textColor = {'var(--black)'}
                headingIntro = {''}
                headingTextColor = {''}
                blockHeading = {'A Stronger Local Food Economy'} 
                subHeading = {''}
                paragraph = {`
                    <p className="globalText">
                        The Farm-to-Table Council is working toward a food economy where businesses are better connected to the infrastructure and opportunities they need to grow.
                    </p>
                    <ul className="globalText"
                        style="line-height:1.5"
                    >
                        <li><strong>Stronger Businesses</strong> — More businesses equipped with the workforce, systems and capacity to pursue growth.</li>
                        <li><strong>Stronger Supply Chains</strong> — Better relationships among the businesses that grow, make, move, serve and purchase food.</li>
                        <li><strong>More Local Sourcing</strong> — Stronger pathways for institutions and businesses to identify and purchase from local suppliers.</li>
                        <li><strong>More Economic Opportunity</strong> — More revenue, jobs and business growth generated within our community.</li>
                    </ul>
                `}
                multiWeekProgram = {false}
                multiEvents = {[]}
                paragraphTwo = {``}
            />

<OneColumn
                backgroundColor = {'var(--grey)'}
                textColor = {'var(--black)'}
                headingIntro = {''}
                headingTextColor = {''}
                blockHeading = {'Access. Investment. Mobility.'} 
                subHeading = {''}
                paragraph = {`
                    <p className="globalText">
                        The Farm-to-Table Council advances the Black Chamber of Memphis' strategy to move businesses from visibility to opportunity—and from opportunity to measurable growth.
                    </p>
                    <h3 className="globalThirdHeading">
                        Three Pillars:
                    </h3>
                    <ul className="globalText"
                        style="line-height:1.5"
                    >
                        <li><strong>Access</strong> — Connections to suppliers, buyers, information, training, procurement opportunities and key partners.</li>
                        <li><strong>Investment</strong> — Strategic, operational, workforce and business-development resources that help businesses become stronger.</li>
                        <li><strong>Mobility</strong> — Pathways that help businesses move from kitchen to shelf, supplier to buyer and smaller customers to larger markets.</li>
                    </ul>
                    <div 
                        style="width:100%; display:flex; alig-items:center; justify-content:center; background:var(--darkGold); padding:2rem 0; margin:4rem 0; border-radius:20px;"
                    >
                        <p 
                            className="globalText"
                            style="color:#000000; font-size: 1.6rem"
                        >
                            The goal is not simply to convene. The goal is to help businesses move.
                        </p>
                    </div>
                `}
                multiWeekProgram = {false}
                multiEvents = {[]}
                paragraphTwo = {``}
            />

            <SingleCTAButton
                singleCtaHeading = {'There is a Seat at the Table for You'}
                singleCtaText = {'Whether you are growing ingredients, developing a product, operating a restaurant, moving goods, purchasing for an institution or investing resources into the food economy, there is an opportunity to participate.'}
                singleCtaButtonLink = {'/programs/farm-to-table/application-form'}
                singleCtaButtonText = {'Join the Table'}
            />
        </main>
    )
}