export const categories = [
    {
        name: "Agriculture & Industry",
        id: "agriculture-industry",
        image: "",
        subCategories: [
            { name: "Agriculture", id: "agriculture", image: "" }
        ]
    },{
        name: "Arts, Culture, Media & Entertainment",
        id: "arts-culture-media-entertainment",
        image: "",
        subCategories: [
            { name: "Arts & Culture", id: "arts-culture", image: "" },
            { name: "Artists", id: "artists", image: "" },
            { name: "Artists & Art Galleries", id: "artists-art-galleries", image: "" },
            { name: "Museums", id: "museums", image: "" },
            { name: "Dance", id: "dance", image: "" },
            { name: "Recording Studios", id: "recording-studios", image: "" },
            { name: "Radio Stations & Broadcasting Companies", id: "radio-stations-broadcasting-companies", image: "" },
            { name: "Video Services", id: "video-services", image: "" },
            { name: "Audio Video Sales & Service", id: "audio-video-sales-service", image: "" },
            { name: "Photographers", id: "photographers", image: "" },
            { name: "Magazines and Publications", id: "magazines-publications", image: "" },
            { name: "Printing", id: "printing", image: "" },
            { name: "Screen Printing", id: "screen-printing", image: "" },
            { name: "Signs", id: "signs", image: "" },
            { name: "Promotional Items", id: "promotional-items", image: "" },
            { name: "Awards", id: "awards", image: "" },
            { name: "Creative Studios", id: "creative-studios", image: "" },
            { name: "Content Production", id: "content-production", image: "" },
        ]
    },{
        name: "Automotive, Transport & Travel",
        id: "automotive-transport-travel",
        image: "",
        subCategories: [
            { name: "Automobile - Dealers", id: "automobile-dealers", image: "" },
            { name: "Automobile - Repair", id: "automobile-repair", image: "" },
            { name: "Automobile - Body & Painting", id: "automobile-body-painting", image: "" },
            { name: "Logistics Services", id: "logistics-services", image: "" },
            { name: "Delivery Services", id: "delivery-services", image: ""},
            { name: "Transportation Services", id: "transportation-services", image: ""},
            { name: "Transmission", id: "transmission", image: "" },
            { name: "Towing", id: "towing", image: "" },
            { name: "Rental Cars", id: "rental-cars", image: "" },
            { name: "Taxicabs", id: "taxicabs", image: "" },
            { name: "Cabs", id: "cabs", image: "" },
            { name: "Limo Services", id: "limo-services", image: "" },
            { name: "Movers", id: "movers", image: "" },
            { name: "Boat Repairing & Painting", id: "boat-repairing-painting", image: "" },
            { name: "Tours", id: "tours", image: "" },
            { name: "Travel Services", id: "travel-services", image: "" }
        ]
    },{
        name: "Beauty, Personal Care & Fitness",
        id: "beauty-personal-care-fitness",
        image: "",
        subCategories: [
            { name: "Beauty Shops", id: "beauty-shops", image: "" },
            { name: "Barbers", id: "barbers", image: "" },
            { name: "Hair Stylists", id: "hair-stylists", image: "" },
            { name: "Nail Salons", id: "nail-salons", image: "" },
            { name: "Manicures", id: "manicures", image: "" },
            { name: "Pedicures", id: "pedicures", image: "" },
            { name: "Day Spas", id: "day-spas", image: "" },
            { name: "Health & Beauty", id: "health-beauty", image: "" },
            { name: "Health & Fitness", id: "health-fitness", image: "" },
            { name: "Martial Arts", id: "martial-arts", image: "" }
        ]
    },{
        name: "Community, Faith & Nonprofit Services",
        id: "community-faith-nonprofit-services",
        image: "",
        subCategories: [
            { name: "Adoption Services", id: "adoption-services", image: "" },
            { name: "Foster Care", id: "foster-care", image: "" },
            { name: "Civil Rights", id: "civil-rights", image: "" },
            { name: "Child Care", id: "child-care", image: "" },
            { name: "Day Care", id: "day-care", image: "" },
            { name: "Schools", id: "schools", image: "" },
            { name: "Employment", id: "employment", image: "" },
            { name: "CPR", id: "cpr", image: "" },
            { name: "Cemeteries", id: "cemeteries", image: "" },
            { name: "Funeral Homes", id: "funeral-homes", image: "" },
            { name: "Monuments", id: "monuments", image: "" },
            { name: "Church Products", id: "church-products", image: "" },
            { name: "Church", id: "church", image: ''},
            { name: "Discipleship Programs", id: "descipleship-programs", image: ''},
            { name: "Community & Faith-based Services", id: "community-faith-based-services", image:''},
            { name: "Choir Robes", id: "choir-robes", image: "" },
            { name: "Nonprofit Organizations", id: "nonprofit-organizations", image: "" },
            { name: "Youth Services", id: "youth-services", image: "" },
            { name: "Community Outreach Programs", id: "community-outreach-programs", image: "" },
            { name: "Social Impact Organizations", id: "social-impact-organizations", image: "" },
            { name: "Emergency Services", id: "emergency-services", image: "" }

        ]
    },{
        name: "Construction, Home Improvement & Trade Services",
        id: "construction-home-improvement-trade-services",
        image: "",
        subCategories: [
            { name: "Construction", id: "construction", image: "" },
            { name: "Contractors", id: "contractors", image: "" },
            { name: "Engineering", id: "engineering", image: "" },
            { name: "Architectural Services", id: "architectural-services", image: ""},
            { name: "Electrical Contractors", id: "electrical-contractors", image: "" },
            { name: "Mechanical Contractors", id: "mechanical-contractors", image: "" },
            { name: "Plumbing", id: "plumbing", image: "" },
            { name: "Heating & Cooling Systems", id: "heating-cooling-systems", image: "" },
            { name: "Air Conditioning Equipment & Systems", id: "air-conditioning-equipment-systems", image: "" },
            { name: "Painting Contractors", id: "painting-contractors", image: "" },
            { name: "Plastering", id: "plastering", image: "" },
            { name: "Fencing", id: "fencing", image: "" },
            { name: "Security Doors & Fences", id: "security-doors-fences", image: "" },
            { name: "Iron Works", id: "iron-works", image: "" },
            { name: "Cabinet Makers", id: "cabinet-makers", image: "" },
            { name: "Interior Decorating", id: "interior-decorating", image: "" },
            { name: "Floors", id: "floors", image: "" },
            { name: "Carpet", id: "carpet", image: "" },
            { name: "Carpet Cleaners", id: "carpet-cleaners", image: "" },
            { name: "Home Repair", id: "home-repair", image: "" },
            { name: "Facilities Maintenance", id: "facilities-maintenance", image: "" },
            { name: "Janitorial Services", id: "janitorial-services", image: "" },
            { name: "Pest Control", id: "pest-control", image: "" },
            { name: "Lawn Care", id: "lawn-care", image: "" }
        ]
    },{
        name: "Events & Weddings",
        id: "events-weddings",
        image: "",
        subCategories: [
            { name: "Weddings", id: "weddings", image: "" },
            { name: "Party Rides", id: "party-rides", image: "" },
            { name: "Carnival Rides", id: "carnival-rides", image: "" },
            { name: "Catering", id: "catering", image: "" },
            { name: "Specialty Decor Rentals", id: "specialty-decor-rentals", image: ""},
            { name: "Event Planning Services", id: "event-planning-services", image: ""},
            { name: "Corporate Events", id: "corporate-events", image: ""}
        ]
    },{
        name: "Food, Dining & Hospitality",
        id: "food-dining-hospitality",
        image: "",
        subCategories: [
            { name: "Restaurants", id: "restaurants", image: "" },
            { name: "Coffee Shops & Cafés", id: "coffee-shops-cafes", image: "" },
            { name: "Fast Food & Takeaways", id: "fast-food-takeaways", image: "" },
            { name: "Catering", id: "catering", image: "" },
            { name: "Hotels", id: "hotels", image: "" },
            { name: "Bars, Breweries & Spirits", id: "bars-breweries-spirits", image: ""},
            { name: "Bakeries & Pastries", id: "bakery-pastries", image: "" },
            { name: "Beverages & Smoothies", id: "beverages-smoothies", image: "" }
        ]
    },{
        name: "Health, Medical & Wellness Services",
        id: "health-medical-wellness-services",
        image: "",
        subCategories: [
            { name: "Doctors", id: "doctors", image: "" },
            { name: "Hospitals", id: "hospitals", image: "" },
            { name: "Home Health", id: "home-health", image: "" },
            { name: "Medical Equipment and Supplies", id: "medical-equipment-supplies", image: "" },
            { name: "Pharmacy", id: "pharmacy", image: "" },
            { name: "Vitamins", id: "vitamins", image: "" },
            { name: "Adolescent Health Care", id: "adolescent-health-care", image: "" },
            { name: "Alcohol & Drug Test", id: "alcohol-drug-test", image: "" },
            { name: "DNA, Drug, Alcohol and Blood Testing", id: "dna-drug-alcohol-blood-testing", image: "" },
            { name: "Medical Laboratory Testing", id:  "medical-laboratory-testing", image: "" },
            { name: "Chiropractor", id: "chiropractor", image: "" },
            { name: "Counseling", id: "counseling", image: "" },
            { name: "Marriage Counseling", id: "marriage-counseling", image: "" },
            { name: "Mental Health", id: "mental-health", image: "" },
            { name: "Psychologist", id: "psychologist", image: "" },
            { name: "Dentist", id: "dentist", image: "" },
            { name: "Optometrist", id: "optometrist", image: "" },
            { name: "Surgeons", id: "surgeons", image: "" },
            { name: "Orthotics, Limbs & Braces", id: "orthotics-limbs-braces", image: "" },
            { name: "Prosthetics & Orthotics", id: "prosthetics-orthotics", image: "" },
            { name: "Vision Care & Eyewear", id: "vision-care-eyewear", image: "" },
            { name: "Optical Stores", id: "optical-stores", image: "" },
            { name: "Community Health Services", id: "community-health-services", image: "" },
            { name: "Wellness Clinics", id: "wellness-clinics", image: "" },
            { name: "Senior Care Services", id: "senior-care-services", image: "" },
            { name: "Life Coach", id: "life-coach", image: "" },
            { name: "Motivational Speaker", id: "motivational-speaker", image: "" },
            { name: "Personal Development", id: "personal-development", image: "" }
        ]
    },{
        name: "Marketing, Advertising & Digital Services",
        id: "marketing-advertising-digital-services",
        image: "",
        subCategories: [
            { name: "Advertising & Advertising Agencies", id: "advertising-advertising-agencies", image: "" },
            { name: "Marketing", id: "marketing", image: "" },
            { name: "Public Relations", id: "public-relations", image: "" },
            { name: "Website Design", id: "website-design", image: "" },
            { name: "Computer Services", id: "computer-services", image: "" },
            { name: "Telephone Equipment & Services", id: "telephone-equipment-services", image: "" },
            { name: "Computer Cartridge", id: "computer-cartridge", image: "" },
            { name: "Ink Cartridge", id: "ink-cartridge", image: "" },
            { name: "Printer Cartridge", id: "printer-cartridge", image: "" },
            { name: "Digital Media Content Creators", id: "digital-media-content-creators", image: "" },
            { name: "Brand Strategy", id: "brand-strategy", image: "" },
            { name: "Social Media Management", id: "social-media-management", image: "" },
            { name: "SEO & Online Marketing", id: "seo-online-marketing", image: "" },
            { name: "Education Software & SaaS Solutions", id: "education-software-saas-solutions", image: "" },
            { name: "Graphic Desing", id: "graphic-design", image: "" },
            { name: "Audio & Video Production", id: "audio-video-production", image: "" },
            { name: "Financial Technology (Fintech)", id: "financial-technology", image: ""},
            { name: "Accounting Software", id: "accounting-software", image: ""},

        ]
    },{
        name: "Professional, Legal & Financial Services",
        id: "professional-legal-financial-services",
        image: "",
        subCategories: [
            { name: "Accountants", id: "accountants", image: "" },
            { name: "Attorneys", id: "attorneys", image: "" },
            { name: "Lawyers", id: "lawyers", image: "" },
            { name: "Bail Bonding", id: "bail-bonding", image: "" },
            { name: "Banks", id: "banks", image: "" },
            { name: "Credit Union", id: "credit-union", image: "" },
            { name: "Financial Planner", id: "financial-planner", image: "" },
            { name: "Investments", id: "investments", image: "" },
            { name: "Stocks & Bonds", id: "stocks-bonds", image: "" },
            { name: "Retirement", id: "retirement", image: "" },
            { name: "Loans", id: "loans", image: "" },
            { name: "Mortgages", id: "mortgages", image: "" },
            { name: "Home Loans", id: "home-loans", image: "" },
            { name: "Insurance", id: "insurance", image: "" },
            { name: "Life Insurance Plan", id: "life-insurance-plan", image: ''},
            { name: "Health Insurance Plan", id: "health-insurance-plan", image: ''},
            { name: "Dental Insurance", id: "dental-insurance", image: "" },
            { name: "Payroll Services", id: "payroll-services", image: "" },
            { name: "Tax Services", id: "tax-services", image: "" },
            { name: "Notary", id: "notary", image: "" },
            { name: "Business Consultants", id: "business-consultants", image: "" },
            { name: "Consultants", id: "consultants", image: "" },
            { name: "Non Profit Consulting", id: "non-profit-consulting", image: "" },
            { name: "Collections", id: "collections", image: "" },
            { name: "Nonprofit Support Services", id: "nonprofit-support-services", image: "" },
            { name: "Grant Writing", id: "grant-writing", image: "" },
            { name: "Succession Planning Solutions", id: "succession-planning-solutions", image: ""},
            { name: "Virtual Receptionist Services", id: "virtual-receptionist-services", image: ''},
            { name: 'Customer Service Outsourcing', id: 'customer-service-outsourcing', image: ''},
            { name: 'Customer Engagement Services', id: 'customer-engagement-services', image: ''},
            { name: 'Professional Organizing Services', id: 'professional-organizing-services', image: ''}
        ]
    },{
        name: "Retail, Shopping & Specialty Stores",
        id: "retail-shopping-specialty-stores",
        image: "",
        subCategories: [
            { name: "Clothing", id: "clothing", image: "" },
            { name: "T-Shirts", id: "t-shirts", image: "" },
            { name: "Uniforms", id: "uniforms", image: "" },
            { name: "Formal Wear - Rentals & Sales", id: "formal-wear-rentals-sales", image: "" },
            { name: "Tuxedos", id: "tuxedos", image: "" },
            { name: "Bridal Services", id: "bridal-services", image: "" },
            { name: "Alterations", id: "alterations", image: "" },
            { name: "Tailors", id: "tailors", image: "" },
            { name: "Seamstress", id: "seamstress", image: "" },
            { name: "Sewing", id: "sewing", image: "" },
            { name: "Reweaving", id: "reweaving", image: "" },
            { name: "Furniture", id: "furniture", image: "" },
            { name: "Hardware", id: "hardware", image: "" },
            { name: "Grocery Stores", id: "grocery-stores", image: "" },
            { name: "Florists", id: "florists", image: "" },
            { name: "Cards & Gifts", id: "cards-gifts", image: "" },
            { name: "Gifts", id: "gifts", image: "" },
            { name: "Jewelry Sales & Repair", id: "jewelry-sales-repair", image: "" },
            { name: "African Imports", id: "african-imports", image: "" },
            { name: "Bookstores", id: "bookstores", image: "" },
            { name: "Beauty & Barber Supplies", id: "beauty-barber-supplies", image: "" },
            { name: "Janitorial Supplies", id: "janitorial-supplies", image: "" },
            { name: "Eyewear & Accessories", id: "eyewear-accessories", image: "" },
            { name: "Online Retailers", id: "online-retailers", image: "" },
            { name: "Lifestyle Brands", id: "lifestyle-brands", image: "" },
            { name: "Computer and Printing Supplies", id: "computer-printing-supplies", image: "" }
        ]
    },{
        name: "Security & Protection Services",
        id: "security-protection-services",
        image: "",
        subCategories: [
            { name: "Security", id: "security", image: "" },
            { name: "Guard Service", id: "guard-service", image: "" },
            { name: "Protection Services", id: "protection-services", image: "" },
            { name: "Locksmiths", id: "locksmiths", image: "" },
            { name: "Burglar Alarms", id: "burglar-alarms", image: "" },
            { name: "Security System Repair & Installation", id: "security-system-repair-installation", image: ''},
            { name: "Alarm & Surveillance System Providers", id: "alarm-surveillance-system-providers", image: ''},
            { name: "Access Control & Intercom Systems", id: "access-control-intercom-systems", image: ''},
            { name: "Security Electronics", id: "security-electronics", image: ""},
        ]
    },{
        name: "Sports, Recreation & Leisure",
        id: "sports-recreation-leisure",
        image: "",
        subCategories: [
            { name: "Golf Courses", id: "golf-courses", image: "" },
            { name: "Sports Leagues and Organized Activities", id: "sports-leagues-organized-activities", image: "" }
        ]
    },{
        name: "Animals, Pets & Veterinary Services",
        id: "animals-pets-veterinary-services",
        image: "",
        subCategories: [
            // { name: "Pet Care & Services", id: "pet-care-services", image: '', }
            { name: "Pet Grooming", id: "pet-grooming", image: "" },
            { name: "Pet Boarding & Daycare", id: "pet-boarding-daycare", image: "" },
            { name: "Dog Walking & Pet Sitting", id: "dog-walking-pet-sitting", image: "" },
            { name: "Pet Training & Behavior Services", id: "pet-training-behavior", image: "" },
            { name: "Mobile Pet Services", id: "mobile-pet-services", image: "" },
            // { name: "Veterinary & Animal Health", id: "veterinary-animal-health", image: ''},
            { name: "Veterinary Clinics & Hospitals", id: "veterinary-clinics-hospitals", image: "" },
            { name: "Emergency & 24-Hour Animal Care", id: "emergency-animal-care", image: "" },
            { name: "Animal Dental Care", id: "animal-dental-care", image: "" },
            { name: "Animal Rehabilitation & Therapy", id: "animal-rehabilitation-therapy", image: "" },
            { name: "Mobile Veterinary Services", id: "mobile-veterinary-services", image: "" },
            // { name: "Pet Retail & Food", id: "pet-retail-food", image: ""},
            { name: "Pet Stores & Boutiques", id: "pet-stores-boutiques", image: "" },
            { name: "Pet Food & Supplies", id: "pet-food-supplies", image: "" },
            { name: "Natural & Specialty Pet Foods", id: "natural-specialty-pet-foods", image: "" },
            { name: "Pet Accessories & Apparel", id: "pet-accessories-apparel", image: "" },
            // { name: "Animal Welfare & Adoption", id: "animal-welfare-adoption", image: ""},
            { name: "Animal Shelters & Rescues", id: "animal-shelters-rescues", image: "" },
            { name: "Pet Adoption Services", id: "pet-adoption-services", image: "" },
            { name: "Animal Welfare Organizations", id: "animal-welfare-organizations", image: "" },
            // { name: "Farm, Livestock & Specialty Animals", id: "farm-livestock-specialty", image: ""},
            { name: "Livestock & Farm Animal Services", id: "livestock-farm-animal-services", image: "" },
            { name: "Equine Services", id: "equine-services", image: "" },
            { name: "Exotic & Specialty Animal Care", id: "exotic-specialty-animal-care", image: "" },
            
        ]
    }
];