export const team = [
    {
        slug: "mark-yates",
        first_name: "Mark",
        last_name: "Yates",
        title: "President & CEO",
        image: '/our-team/Mark.png',
        bio: `<p>Mark Yates is the Tennessee Valley Authority's regional vice president for the West Region. A native Memphian, Yates holds an Executive Master of Business Administration degree from Vanderbilt Owen Graduate School of Management and a Bachelor of Arts from Howard University in Economics and Finance. A trained process thinker with a Six Sigma certification, Yates has led numerous teams and organizations on successful endeavors throughout his career.</p>
                <p>A seasoned board member and community advocate, Yates currently serves or has served as Chairman of River City Capital, a Community Development Finance Institution, Memphis Shelby County Land Use Control Board, Juvenile Court Foster Care Review Board, Memphis Shelby County Industrial Development Vice Chair, member of the 100 Black Men organization, Shelby County Health and Education Board Treasurer, Shelby County Board of Equalization, LeMoyne-Owen College Finance Professor, DCS Community Advisory Board, Regional Medical Center Board, Star Academy Charter School, Leadership Memphis 2019, Omega Psi `,
        email: "mark@bbamemphis.com",
        vCardBioSection: `<p>Mark Yates is the Tennessee Valley Authority's regional vice president for the West Region. A native Memphian, Yates holds an Executive Master of Business Administration degree from Vanderbilt Owen Graduate School of Management and a Bachelor of Arts from Howard University in Economics and Finance. A trained process thinker with a Six Sigma certification, Yates has led numerous teams and organizations on successful endeavors throughout his career.</p>`
    },
    {
        slug: "alan-gumbel",
        first_name: "Alan",
        last_name: "Gumbel",
        title: "COO",
        image: '/our-team/Alan.png',
        bio: `<p>Alan Gumbel became the Chief Operating Officer of the Black Business Association of Memphis (BBA Memphis) in January 2023. Alan brings years of executive and senior leadership to his role; having served as Executive Director of the Memphis Academy of Health Sciences, the Greater Memphis Alliance for a Competitive Workforce, and Deputy Director of Programs of the City of Memphis Workforce Investment Network.</p>
                <p>In addition to his senior leadership roles, Alan has extensive experience planning, developing, managing, and evaluating community economic development and workforce development programs in the Mid-South and across the nation as a business owner and consultant. Alan spent his early career establishing programs that supported technology transfer for Arkansas-based businesses for the Arkansas Science and Technology Authority before moving to Memphis and working as a policy analyst for the Lower Mississippi Delta Development Commission. Mr. Gumbel earned a Bachelor of Arts in Political Science from Emporia State University in Kansas.</p>
                <p>Alan has served his community as a board member of the Southeast Memphis Community Development Corporation, Whitehaven Community Development Corporation, Family Services of the Mid-South and Memphis Center for Independent Living. He is a graduate of Leadership Memphis Executive Program (2018). He also serves as a Tennessee state coordinator of the Delta Grassroots Caucus that promotes community and economic development in the eight state Delta region.</p>
                <p>Alan is excited to join the BBA Memphis team and sees it as an opportunity to merge his personal passion for small business development with his executive nonprofit experience in service of a greater and more prosperous Memphis.</p>`,
        email : 'alan@bbamemphis.com',
        vCardBioSection : `<p>Alan Gumbel became the Chief Operating Officer of the Black Business Association of Memphis (BBA Memphis) in January 2023. Alan brings years of executive and senior leadership to his role; having served as Executive Director of the Memphis Academy of Health Sciences, the Greater Memphis Alliance for a Competitive Workforce, and Deputy Director of Programs of the City of Memphis Workforce Investment Network.</p>`
    },
    // {
    //     slug: "alisha-williamson",
    //     first_name: "Alisha",
    //     last_name: "Williamson",
    //     title: "Program Manager, Workforce & Talent Acquisition",
    //     image: '/our-team/Alisha.png',
    //     bio: `<p>Alisha Williamson, a Memphis, TN native, is a driven, passionate, and experienced community engagement professional. In her role as Strategic Project Administrator, Alisha will manage internal and external special projects in coordination with partners, stakeholders and/or organizations on behalf of the CEO. Her success streams from helping companies, nonprofit organizations, and agencies with consumer and brand engagement projects for over 10yrs.</p>
    //             <p>Alisha's background in marketing and communications and her passion for community involvement has helped her spread her creative wings in all areas of brand management, consumer engagement, and digital marketing strategies. She is a woman of many hats, but her favorite is being a mother. She works hard and balances her career as she continues to establish financial security. Alisha's goal is to empower and educate Black businesses on the value of their worth through an entrepreneur mindset.</p>`
    // },
    // {
    //     slug: "eugenia-grey",
    //     first_name: "Dr Eugenia",
    //     last_name: "Gray",
    //     title: "Program Manager, Technology Support",
    //     image: '/our-team/Dr-Eugenia.png',
    //     bio: `<p>As the BBA's Small Business Programs Manager, Eugenia brings 30 years of professional experience, specializing in strategic business planning, communications, media/PR, publicity, marketing, branding, and development, which includes her private practice business consultancy, Allegis Development Group, LLC—operating in diverse service industries. Her experience has been in the non-profit, government relations, PR/media, hospitality, commercial real estate, engineering, transportation, and logistics. She serves as a business coach/consultant and certified training facilitator of essential business skills and develops DEI&A strategies to minority business owners to acquire industry-related certifications for contract procurement within their respective industries. She has coordinated communications strategies, marketing, product branding, business program development and strategy efforts for clients such as the Memphis Urban League, Urban League of Greater Chattanooga, Rexam Beverage Can Americas, Jabil Global Supply Chain, TBC Corporation, Kroger KMA – Delta Region, JCore International, National Civil Rights Museum, M.S. Carriers, Lottworth Enterprises, and C.H. Robinson Worldwide. In previous roles she served as the Director of Entrepreneurship and Economic Development for a national non-profit and was the former Vice President of Corporate Affairs & Communications for a public strategies and government relations firm. Eugenia is also the associate producer of Greater Memphis Media [home of the Brian Clay Chronicles], an award-winning, social justice journalism company, and co-founder/managing partner of a full-service 3PL logistics, freight brokerage and transportation company.</p>
    //             <p>Originally from Dayton, Ohio, but raised in Memphis, Eugenia graduated from Mitchell High School and studied International Business Management and Marketing at Central State University and Mass Communications at Xavier University (Williams School of Business). She holds a Bachelor of Business Administration (BBA) degree in Marketing and a Master of Science (MBA) in Mass Communications and Public Relations. She has also studied many of the scholastics of the Bible and completed her Doctor of Philosophy (PhD) in Practical Christian Theology in 2017. She enjoys watching sports, traveling, reading, movies, dancing, roller skating and spending time with family.</p>`
    // },
    {
        slug: "jasmine-bowden",
        first_name: "Jasmine",
        last_name: "Bowden",
        title: "Program Manager, BCOM Business Booster",
        image: '/our-team/Jasmine.png',
        bio: `<p>Jasmine Bowden is a strategic planner and servant leader with experience in developing programs, cultivating partnerships, and managing logistics for nonprofits, political action committees, and community development organizations. Drawing from an urban sociology lens, Bowden has an interest in economic development, resiliency planning, and cultural preservation. She holds a Master of City and Regional Planning from the University of Memphis and a Bachelor of Arts in American Studies and Sociology from the University of Tennessee at Knoxville. Jasmine is an alum of both the Congressional Black Caucus Foundation’s Emerging Leaders and American University’s WeLead campaign training program. The Black Business Association of Memphis (BBA) recently named Bowden as its Grant Manager where she will oversee its new Business Booster Program which provides technical assistance and comprehensive training to aid local restaurant, food, tourism, and hospitality businesses. Previously, Bowden served as the Program Manager for The Works, Inc. where she convened and developed programming for the Blight Elimination Steering Team (BEST), Strategic Code Enforcement Management Academy (SCEMA), and oversaw the Good Neighbor Grant for commercial property improvements. Prior to her role at The Works, Bowden gained experience in Washington, DC where she convened national organizations to push for equitable access to sexual and reproductive health care services for communities of color. During the 2018 election cycle, Jasmine coordinated supporter events, resulting in the (re)election of 34 members of Congress and more than 300 candidates to state and local offices across the country.Outside her professional commitments, Jasmine enjoys curating social gatherings, hiking, and serving others. She is an active member of Memphis Urban League Young Professionals, a Gen Next PAC Board Member, and a Southern Black Girls and Women's Consortium Wisdom Councilmember.</p>`,
        email : 'jasmine@bbamemphis.com',
        vCardBioSection : `<p>Jasmine Bowden is a strategic planner and servant leader with experience in developing programs, cultivating partnerships, and managing logistics for nonprofits, political action committees, and community development organizations. Drawing from an urban sociology lens, Bowden has an interest in economic development, resiliency planning, and cultural preservation. She holds a Master of City and Regional Planning from the University of Memphis and a Bachelor of Arts in American Studies and Sociology from the University of Tennessee at Knoxville. Jasmine is an alum of both the Congressional Black Caucus Foundation’s Emerging Leaders and American University’s WeLead campaign training program. The Black Business Association of Memphis (BBA) recently named Bowden as its Grant Manager where she will oversee its new Business Booster Program which provides technical assistance and comprehensive training to aid local restaurant, food, tourism, and hospitality businesses. Previously, Bowden served as the Program Manager for The Works, Inc. where she convened and developed programming for the Blight Elimination Steering Team (BEST), Strategic Code Enforcement Management Academy (SCEMA), and oversaw the Good Neighbor Grant for commercial property improvements. Prior to her role at The Works, Bowden gained experience in Washington, DC where she convened national organizations to push for equitable access to sexual and reproductive health care services for communities of color. During the 2018 election cycle, Jasmine coordinated supporter events, resulting in the (re)election of 34 members of Congress and more than 300 candidates to state and local offices across the country.Outside her professional commitments, Jasmine enjoys curating social gatherings, hiking, and serving others. She is an active member of Memphis Urban League Young Professionals, a Gen Next PAC Board Member, and a Southern Black Girls and Women's Consortium Wisdom Councilmember.</p>`
    },
]