export const symbolicManna = {
    memberStatus: true,
    id : "symbolic-manna",
    businessName : "Symbolic Manna",
    bannerImage : "",
    profileLogo : "symbolic-manna",
    profileDescription : "Symbolic Manna Catering is a Memphis, TN–based full-service catering company offering custom event menus, buffet services, and off-site catering for weddings, reunions, corporate gatherings, and social events.",
    profileCategory : [
        "food-drinks-hospitality",
        "event-arts-entertainment",
    ],
    profileSubCategory : [
        "bakeries-catering-event-food-services",
        "event-catering-concession-services",
    ],
    profileBusinessDescription : ``,
    gallery : [],
    businessHours : {
        monHours : "8:30 am - 5 pm",
        tueHours : "8:30 am - 5 pm",
        wedHours : "8:30 am - 5 pm",
        thuHours : "8:30 am - 5 pm",
        friHours : "8:30 am - 5 pm",
        satHours : "8:30 am - 5 pm",
        sunHours : "Closed"
    },
    addressLink : "https://share.google/klXl4xcfMfe1Drhow",
    address : "1514 Ely St, Memphis, TN 38106",
    email : "chefstephenwalker@att.net",
    website : "",
    telNumber : "9014131425",
    facebook : "https://www.facebook.com/symbolicmannallc/",
    instagram : "",
    youtube : "",
    linkedIn : "",
    linktree : "",
    twitter: "",
    tiktok : "",
    pinterest : ""
}