import { MembersListType } from './../membersListType'

export const peteMitchellAssos : MembersListType = {
    memberStatus: false,
    id : "Pete Mitchell & Associates-nc.",
    businessName : "Pete Mitchell & Assoc., Inc.",
    bannerImage : "",
    profileLogo : "Black-chamber-of-Memphis",
    profileDescription : "Pete Mitchell & Associates is a Memphis-based independent insurance agency offering auto, home, business, life, and health coverage—backed by local leadership, multicarrier choices, and trusted service since 1975.",
    profileCategory : [
        "professional-legal-financial-services",
    ],
    profileSubCategory : [
        "insurance",
        "stocks-bonds",
        "life-insurance-plan",
        "health-insurance-plan",
    ],
    categoryTag: [
        "auto insurance",
        'car insurance',
        'motorcycle insurance',
        'boat insurance',
        'rv insurance',
        'renters coverage',
        'commercial liability',
        'workers compensations',
        'bonds',
        'independent insurance brokerage',
    ],
    profileBusinessDescription : ``,
    gallery : [],
    businessHours : [
        { day : "Monday", hours : '9am - 5pm'},
        { day : "Tuesday", hours : '9am - 5pm'},
        { day : "Wednesday", hours : '9am - 5pm'},
        { day : "Thursday", hours : '9am - 5pm'},
        { day : "Friday", hours : '9am - 5pm'},
        { day : "Saturday", hours : 'Closed'},
        { day : "Sunday", hours : 'Closed'},
    ],
    addressLink : "https://g.co/kgs/PNK5LuD",
    address : "4216 Millbranch Rd, Memphis, Tn 38116",
    email : "dedric.pearson@petemitchellins.com",
    website : "https://petemitchellins.com/",
    telNumber : "9013456176",
    facebook : "https://www.facebook.com/PetemitchellInsurance/",
    instagram : "https://www.instagram.com/petemitchellins/",
    youtube : "",
    linkedIn : "https://www.linkedin.com/company/pete-mitchell-&-associates/?viewAsMember=true",
    linktree : "",
    twitter: "",
    tiktok : "",
    pinterest : ""
}