export const kudzukian = {
    memberStatus: true,
    id : "kudzukian",
    businessName : "Kudzukian",
    bannerImage : "",
    profileLogo : "kudzukian",
    profileDescription : "KUDZUKIAN is a Memphis-based branded audio-visual studio specializing in podcast production and event production. Founded in 2014, they deliver turnkey storytelling—from podcasts to live experiences—backed by creative vision and execution.",
    profileCategory : [
        "marketing-advertising-media",
    ],
    profileSubCategory : [
        "video-production-multimedia",
        "digital-media-content-creators",
        "voiceover-audio-production-services",
        "radio-tv-show-development",
        "podcasting-audio-content-production",
    ],
    profileBusinessDescription : ``,
    gallery : [{image : "", alt : ""}],
    businessHours : {
        monHours : "10am - 5pm",
        tueHours : "10am - 5pm",
        wedHours : "10am - 5pm",
        thuHours : "10am - 5pm",
        friHours : "10am - 5pm",
        satHours : "Closed",
        sunHours : "Closed"
    },
    addressLink : "https://share.google/SuhxTtRL5s5YGKESf",
    address : "7777 Walnut Grove Rd, Memphis, TN 38120",
    email : "larry@kudzukian.com",
    website : "https://kudzukian.com/",
    telNumber : "9015126767",
    facebook : "",
    instagram : "https://www.instagram.com/kudzukian/",
    youtube : "https://www.youtube.com/channel/UCKLZ5nYI1HXUW-l7Bh9z3fA",
    linkedIn : "https://www.linkedin.com/company/kudzukian",
    linktree : "",
    twitter: "https://twitter.com/kudzukianmedia",
    tiktok : "",
    pinterest : ""
}