export const mission360strategies = {
    memberStatus: true,
    id : "mission360-strategies",
    businessName : "Mission360 Strategies",
    bannerImage : "",
    profileLogo : "mission360-strategies",
    profileDescription : "Mission360 Strategies, based in Germantown, TN, delivers customized strategic planning, resource development, and donor engagement services for nonprofits—driven by equity, innovation, and sustainable growth under the leadership of Tiffany Graham.",
    profileCategory : [
        "business-finance-professional-services",
        "community-government-non-profits",
    ],
    profileSubCategory : [
        "business-consulting-coaching",
        "strategic-planning-organizational-development",
        "ngo-charities",
        "economic-workforce-development",
    ],
    profileBusinessDescription : ``,
    gallery : [{image : "", alt : ""}],
    businessHours : {
        monHours : "",
        tueHours : "",
        wedHours : "",
        thuHours : "",
        friHours : "",
        satHours : "",
        sunHours : ""
    },
    addressLink : "",
    address : "",
    email : "tiffany@mission360strategies.com",
    website : "https://mission360strategies.com/",
    telNumber : "",
    facebook : "https://www.facebook.com/profile.php?id=61567735566658",
    instagram : "",
    youtube : "",
    linkedIn : "https://www.linkedin.com/company/mission360-strategies/",
    linktree : "",
    twitter: "",
    tiktok : "",
    pinterest : ""
}