export const diamondSafetyTraining = {
    memberStatus: true,
    id : "diamond-safety-training",
    businessName : "Diamond Safety & Training",
    bannerImage : "",
    profileLogo : "diamond-safety-training",
    profileDescription : "Diamond Safety & Training offers Memphis-area businesses AI-enhanced safety technologies, wearable monitoring, LMS-driven OSHA compliance, and certified coaching to foster proactive, tech-forward workplace safety.",
    profileCategory : [
        "business-finance-professional-services",
        "technology-communications",
        "education-training-youth-development",
        "industrial-engineering-manufacturing",
    ],
    profileSubCategory : [
        "business-consulting-coaching",
        "it-support-software-development",
        "skills-development-training-centres",
        "engineering-services",
    ],
    profileBusinessDescription : ``,
    gallery : [{image : "", alt : ""}],
    businessHours : {
        monHours : "",
        tueHours : "",
        wedHours : "",
        thuHours : "",
        friHours : "",
        satHours : "",
        sunHours : ""
    },
    addressLink : "",
    address : "",
    email : "",
    website : "",
    telNumber : "",
    facebook : "",
    instagram : "",
    youtube : "",
    linkedIn : "",
    linktree : "",
    twitter: "",
    tiktok : "",
    pinterest : ""
}